import 'fake-indexeddb/auto';
import {beforeEach,describe,it,expect,vi} from 'vitest';
vi.mock('@/services/learning-content.service',()=>({executeLearningContent:vi.fn()}));
import {executeLearningContent} from '@/services/learning-content.service';
import {decisionSource,newEntry,saveDraft,queueEntry,syncPortfolio,localEntries,portfolioDb,readPortfolio} from '@/services/ethics-portfolio.service';
import {newAttempt,extendAttempt,STONE_CLASS_ID} from '@/services/stone.service';
// @ts-expect-error Separately deployed backend module.
import {cleanEntry,choiceContext,ethicsPortfolioAction} from '../../functions/learning-content/src/ethics-portfolio.js';
const choices=['listen','needs','paid','bargain','investigate','balance','preserve','delegate','publish','council'];
const a=extendAttempt(newAttempt('alice',STONE_CLASS_ID,false),choices);
const draft=()=>({...newEntry('alice',STONE_CLASS_ID,decisionSource(a,1)),answers:['Distribute by need.','Needs differ, but equal shares are predictable.','I favour need with public reasons.']});
const call=vi.mocked(executeLearningContent);
beforeEach(async()=>{await portfolioDb.entries.clear();await portfolioDb.outbox.clear();call.mockReset();});
describe('reasoning records',()=>{
 it('reconstructs the actual source independently of supplied labels',()=>{const e=draft();const clean=cleanEntry({...e,submitted:true},null,{open:false});expect(clean.source.label).toContain('Distribute by need');expect(clean.source.outcome).toBeTruthy();expect(()=>choiceContext(['listen'],0)).toThrow();expect(()=>choiceContext(choices,99)).toThrow();});
 it('keeps the submitted original and allows only an opened reconsideration',()=>{const e=cleanEntry({...draft(),submitted:true},null,{open:false});expect(()=>cleanEntry({...e,answers:['Changed','why','now']},e,{open:true})).toThrow('preserved');expect(()=>cleanEntry({...e,reconsideration:'A peer noticed another cost.'},e,{open:false})).toThrow('not opened');expect(cleanEntry({...e,reconsideration:'I retain it for a stronger reason.'},e,{open:true}).answers).toEqual(e.answers);expect(()=>cleanEntry({...e,reconsideration:'late'},e,{open:true,deadline:'2020-01-01'})).toThrow('deadline');});
 it('accepts reading entries and rejects unsafe links and incomplete answers',()=>{const e={...draft(),source:{kind:'reading',title:'Ma’at',passage:'A specific passage',url:'https://example.org/reading'},submitted:true};expect(cleanEntry(e,null,{open:false}).source.kind).toBe('reading');expect(()=>cleanEntry({...e,source:{...e.source,url:'javascript:alert(1)'}},null,{})).toThrow();expect(()=>cleanEntry({...e,answers:['','','']},null,{})).toThrow();});
});
describe('account-scoped offline persistence',()=>{
 it('keeps drafts and queued originals across failure, and retries the same revision',async()=>{const e=draft();await saveDraft(e);expect((await localEntries('alice',STONE_CLASS_ID))[0].answers).toEqual(e.answers);expect(await localEntries('bob',STONE_CLASS_ID)).toEqual([]);await queueEntry({...e,submitted:true});call.mockRejectedValueOnce(Error('offline'));await expect(syncPortfolio('alice',STONE_CLASS_ID)).rejects.toThrow('offline');expect(await portfolioDb.outbox.count()).toBe(1);call.mockResolvedValue({saved:true});await syncPortfolio('alice',STONE_CLASS_ID);expect(await portfolioDb.outbox.count()).toBe(0);expect(call.mock.calls[0][0]).toEqual(call.mock.calls[1][0]);});
 it('sends originals before reconsiderations and preserves conflicts',async()=>{let e=await queueEntry({...draft(),submitted:true});e=await queueEntry({...e,reconsideration:'I still agree, after discussing the alternatives.'});call.mockResolvedValueOnce({saved:true}).mockRejectedValueOnce(Error('another device'));await expect(syncPortfolio('alice',STONE_CLASS_ID)).rejects.toThrow('another device');expect(await portfolioDb.outbox.count()).toBe(1);expect((await localEntries('alice',STONE_CLASS_ID))[0].reconsideration).toContain('still agree');expect(call.mock.calls.map(c=>(c[0].entry as any).revision)).toEqual([1,2]);});
 it('does not replace an unsent draft with a newer remote revision',async()=>{const e=draft();await saveDraft(e);call.mockResolvedValue({teacher:false,settings:{open:false},entries:[{...e,revision:2,answers:['remote','remote','remote']}]});await readPortfolio('alice',STONE_CLASS_ID);expect((await localEntries('alice',STONE_CLASS_ID))[0].answers).toEqual(e.answers);});
 it('prevents an older tab draft from replacing a submitted original',async()=>{const e=draft();await saveDraft(e);await queueEntry({...e,submitted:true});await expect(saveDraft({...e,answers:['stale','','']})).rejects.toThrow('another tab');expect((await localEntries('alice',STONE_CLASS_ID))[0].submitted).toBe(true);expect((await localEntries('alice',STONE_CLASS_ID))[0].answers).toEqual(e.answers);});
 it('never syncs preview writing',async()=>{await queueEntry({...draft(),preview:true,submitted:true});await syncPortfolio('alice',STONE_CLASS_ID);expect(call).not.toHaveBeenCalled();});
});
function fakeDb(){const rows=new Map<string,any>();return {rows,getDocument:vi.fn(async(_db:string,col:string,id:string)=>{if(col==='classes')return {teacherId:'teacher'};const row=rows.get(id);if(!row)throw Object.assign(Error('missing'),{code:404});return row;}),createDocument:vi.fn(async(_db:string,_col:string,id:string,data:any,_permissions:any[])=>{if(rows.has(id))throw Object.assign(Error('duplicate'),{code:409});const row={...data,$id:id,$createdAt:new Date().toISOString()};rows.set(id,row);return row;}),listDocuments:vi.fn(async()=>({documents:[]}))};}
describe('server authorization and concurrency',()=>{
 it('rejects nonmembers, other teachers, wrong classes and student stage changes',async()=>{const db=fakeDb(),base={db,databaseId:'main',body:{action:'readEthicsPortfolio',classId:STONE_CLASS_ID},userId:'outsider',profile:{role:'student'},memberClassIds:new Set()};await expect(ethicsPortfolioAction(base)).rejects.toThrow('membership');await expect(ethicsPortfolioAction({...base,profile:{role:'teacher'}})).rejects.toThrow('membership');await expect(ethicsPortfolioAction({...base,body:{...base.body,classId:'other'}})).rejects.toThrow('Ethics');await expect(ethicsPortfolioAction({...base,memberClassIds:new Set([STONE_CLASS_ID]),body:{...base.body,action:'setEthicsPortfolioStage',open:true}})).rejects.toThrow('teacher');});
 it('uses authenticated ownership, creates immutable private revisions, and handles retries/conflicts',async()=>{const db=fakeDb(),entry={...draft(),revision:1,submitted:true,userId:'spoofed'},base={db,databaseId:'main',body:{action:'saveEthicsPortfolio',classId:STONE_CLASS_ID,entry},userId:'alice',profile:{role:'student'},memberClassIds:new Set([STONE_CLASS_ID])};await ethicsPortfolioAction(base);await ethicsPortfolioAction(base);expect(db.rows.size).toBe(1);expect([...db.rows.values()][0].userId).toBe('alice');expect(db.createDocument.mock.calls[0][4]).toEqual([]);await expect(ethicsPortfolioAction({...base,body:{...base.body,entry:{...entry,answers:['different','reason','judgment']}}})).rejects.toThrow('another device');await expect(ethicsPortfolioAction({...base,body:{...base.body,entry:{...entry,revision:3}}})).rejects.toThrow('earlier');});
});
