import Dexie,{type EntityTable} from 'dexie';
import {executeLearningContent} from './learning-content.service';
import {assessYoung,assessDriver} from '../../functions/learning-content/src/young-content.js';
import type {Episode} from '../../functions/learning-content/src/episode-catalog.js';
export interface EpisodeAttempt {attemptId:string;userId:string;classId:string;episode:string;version:number;assignmentId:string;choices:string[];driverAttempts?:number[][];revision:number;status:'active'|'complete';preview:boolean;pending:boolean;createdAt:string;updatedAt:string;}
export interface EpisodeWriting {id:string;userId:string;attemptId:string;mode:'question'|'feedback';text:string;answer?:string;state:string;createdAt:string;}
export const episodeDb=new Dexie('LearningIsFunEpisodes') as Dexie & {attempts:EntityTable<EpisodeAttempt,'attemptId'>;writing:EntityTable<EpisodeWriting,'id'>};
episodeDb.version(1).stores({attempts:'attemptId,[userId+classId],userId,updatedAt',writing:'id,[userId+attemptId],userId'});
export const attemptsFor=async(userId:string,classId:string)=>(await episodeDb.attempts.where('[userId+classId]').equals([userId,classId]).toArray()).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
export function makeEpisodeAttempt(userId:string,e:Episode,preview:boolean):EpisodeAttempt {return {attemptId:crypto.randomUUID(),userId,classId:e.classId,episode:e.id,version:e.version,assignmentId:e.assignmentId,choices:[],revision:0,status:'active',preview,pending:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};}
export function advanceEpisode(a:EpisodeAttempt,choices:string[],driverAttempts=a.driverAttempts||[]):EpisodeAttempt {const result=assessYoung(choices),fare=assessDriver(driverAttempts),old=a.driverAttempts||[];if(driverAttempts.length&&choices.length!==10)throw new Error('Finish the journey before the driver check.');if(choices.length<a.choices.length||!a.choices.every((c,i)=>c===choices[i])||driverAttempts.length<old.length||!old.every((v,i)=>JSON.stringify(v)===JSON.stringify(driverAttempts[i])))throw new Error('Start a new replay to change an earlier choice.');return {...a,choices:choices.slice(),driverAttempts:driverAttempts.map(v=>v.slice()),revision:choices.length+driverAttempts.length,status:result.complete&&fare.passed?'complete':'active',pending:!a.preview,updatedAt:new Date().toISOString()};}
export const readEpisodes=(classId:string)=>executeLearningContent<{episodes:Episode[];attempts:EpisodeAttempt[];preview:boolean}>({action:'readEpisodes',classId});
export async function saveEpisode(a:EpisodeAttempt){if(a.preview)return;await executeLearningContent({action:'saveEpisode',classId:a.classId,episode:a.episode,version:a.version,attempt:a});await episodeDb.transaction('rw',episodeDb.attempts,async()=>{const current=await episodeDb.attempts.get(a.attemptId);if(current?.revision===a.revision)await episodeDb.attempts.update(a.attemptId,{pending:false});});}
export async function episodeAI(a:EpisodeAttempt,mode:'question'|'feedback',text:string){return executeLearningContent<{id:string;text:string;answer:string;state:string}>({action:'episodeAI',classId:a.classId,episode:a.episode,version:a.version,attempt:a,mode,text});}
export function validEpisodeMessage(event:MessageEvent,source:Window|null,channel:string,e:Episode){const m=event.data;return event.source===source&&event.origin===location.origin&&m?.protocol==='episode-v1'&&m.episode===e.id&&m.version===e.version&&(m.type==='ready'||m.channel===channel&&['started','save','complete','replay','question','analysis','exit'].includes(m.type));}

export async function readEpisodeWriting(a:EpisodeAttempt){const result=await executeLearningContent<{writing:EpisodeWriting[]}>({action:"episodeWriting",classId:a.classId,episode:a.episode,version:a.version,attempt:a});for(const row of result.writing)await episodeDb.writing.put({...row,userId:a.userId,attemptId:a.attemptId});}
