import { ResourceTitleField, ResourceLinkField } from '@/components/common/ResourceFields';
import { PublicReadingChoice } from '@/components/texts/TextPublicSharing';
import { TextClassChoices } from './TextClassChoices';
import { useState } from 'react';
import { Button } from '@/components/common/Button';
import { Modal } from '@/components/common/Modal';
import { Markdown } from '@/components/common/Markdown';
import { MarkdownPasteEditor } from '@/components/common/MarkdownPasteEditor';
import { TextFileUpload } from '@/components/texts/TextFileUpload';
import { createText, splitParagraphs } from '@/services/text.service';
import type { TextPurpose } from './TextPurpose';
export function CreateTextModal({teacherId,classes,onClose,initialClassIds=[],onChooseExisting,initialMode='full',assignedAt,allowTitleOnly=false}:{teacherId:string;classes:Array<{id:string;name:string}>;onClose:()=>void;initialClassIds?:string[];onChooseExisting?:()=>void;initialMode?:'full'|'link';assignedAt?:string;allowTitleOnly?:boolean}) {
  const [title,setTitle]=useState(''); const [author,setAuthor]=useState(''); const [mode,setMode]=useState<'full'|'link'>(initialMode); const [externalUrl,setExternalUrl]=useState(''); const [raw,setRaw]=useState(''); const [paragraphs,setParagraphs]=useState<string[]>([]); const [selected,setSelected]=useState(new Set<string>(initialClassIds)); const [busy,setBusy]=useState(false); const preview=paragraphs.length?paragraphs:splitParagraphs(raw);
  const [publicReadEnabled,setPublicReadEnabled]=useState(true);
  const [purposes,setPurposes]=useState<Record<string,TextPurpose>>({});
  const [dates,setDates]=useState<Record<string,string>>({});
  const [originalPdf,setOriginalPdf]=useState<File>(); const [saveError,setSaveError]=useState('');
  const valid = title.trim() && (!externalUrl.trim()||/^https?:\/\//i.test(externalUrl.trim())) && (mode==='link' ? (allowTitleOnly || /^https?:\/\//i.test(externalUrl)) : (preview.length > 0 || Boolean(originalPdf)));
  const saveButton=<Button loading={busy} disabled={!valid} onClick={()=>{setBusy(true);void createText({teacherId,publicReadEnabled,title:title.trim(),author:author.trim(),source:'',paragraphs:mode==='full'?preview:[],originalPdf:mode==='full'?originalPdf:undefined,schedule:assignedAt?{assignedAt}:undefined,classIds:[...selected],classDates:dates,classPurposes:purposes,contentMode:mode,externalUrl:externalUrl.trim()}).then(onClose).catch(cause=>setSaveError(cause instanceof Error?cause.message:'Could not save the text.')).finally(()=>setBusy(false))}}>Save text</Button>;
  return <Modal open onClose={()=>!busy&&onClose()} title="Add text"><div className="space-y-3 max-h-[75vh] overflow-auto">{onChooseExisting&&<Button variant="secondary" disabled={busy} onClick={onChooseExisting}>Choose existing text instead</Button>}{saveError&&<p role="alert" className="text-sm text-red-700">{saveError}</p>}<div className="grid grid-cols-2 gap-2 rounded-lg bg-gray-100 p-1"><button className={`rounded-md px-3 py-2 text-sm font-medium ${mode==='full'?'bg-white shadow-sm':''}`} onClick={()=>setMode('full')}>Full text</button><button className={`rounded-md px-3 py-2 text-sm font-medium ${mode==='link'?'bg-white shadow-sm':''}`} onClick={()=>setMode('link')}>Link only</button></div><PublicReadingChoice enabled={publicReadEnabled} onChange={setPublicReadEnabled}/><ResourceTitleField value={title} onChange={setTitle}/><input className={input} placeholder="Author" value={author} onChange={e=>setAuthor(e.target.value)}/><TextClassChoices classes={classes} selected={selected} onSelected={setSelected} dates={dates} onDates={setDates} purposes={purposes} onPurposes={setPurposes}/>{mode==='link'?<ResourceLinkField value={externalUrl} onChange={setExternalUrl}/>:<><ResourceLinkField value={externalUrl} onChange={setExternalUrl}/><TextFileUpload onBusyChange={setBusy} onImport={(content,file)=>{setRaw(content);setParagraphs([]);setOriginalPdf(file)}}/>{saveButton}<MarkdownPasteEditor value={raw} onChange={value=>{setRaw(value);setParagraphs([])}} rows={10}/><details><summary className="cursor-pointer text-sm font-medium">Paragraph preview ({preview.length})</summary><div className="mt-2 space-y-2">{preview.map((p,i)=><div key={i} className="rounded-lg border bg-white p-3"><p className="mb-2 text-xs text-gray-400">Paragraph {i+1}</p><Markdown content={p}/></div>)}</div></details></>}{mode==='link'&&saveButton}</div></Modal>;
}
const input='w-full rounded-lg border border-gray-300 px-3 py-2 text-sm';
