import { useState } from 'react';
import { executeLearningContent } from '@/services/learning-content.service';
export function PublicReadingChoice({enabled,onChange}:{enabled:boolean;onChange:(value:boolean)=>void}) {
  return <div className="rounded-xl border bg-slate-50 p-3 text-sm"><label className="flex gap-2 font-medium"><input type="checkbox" checked={enabled} onChange={e=>onChange(e.target.checked)}/>Anyone with the link can read</label><p className="mt-1 text-xs text-slate-600">On by default for new texts. Includes the uploaded original; public links work before class due dates. Turn off for class-only material. Student work stays private.</p></div>;
}
export function TextPublicSharing({textId}:{textId:string}) {
  const [open,setOpen]=useState(false),[enabled,setEnabled]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const load=async()=>{setOpen(true);setBusy(true);setError('');try{const result=await executeLearningContent<{enabled:boolean}>({action:'readTextPublicSharing',textId});setEnabled(result.enabled);}catch(e){setError(e instanceof Error?e.message:'Cannot load sharing');}finally{setBusy(false);}};
  return <div className="text-sm"><button type="button" className="min-h-10 rounded-lg border bg-white px-3 text-slate-700" onClick={()=>open?setOpen(false):void load()} aria-expanded={open}>Link access</button>{open&&<div className="mt-2 max-w-sm space-y-2 rounded-xl border bg-white p-3 text-slate-700"><label className="flex items-start gap-2"><input type="checkbox" className="mt-1" disabled={busy||enabled===null} checked={enabled===true} onChange={async e=>{const next=e.target.checked;setBusy(true);setError('');try{const result=await executeLearningContent<{enabled:boolean}>({action:'setTextPublicSharing',textId,enabled:next});setEnabled(result.enabled);}catch(cause){setError(cause instanceof Error?cause.message:'Could not update sharing');}finally{setBusy(false);}}}/>Anyone with the link can read</label><p className="text-xs">Shares the published text and its original uploaded file, even before class due dates. Links can be forwarded. Only enable this for material you are allowed to share publicly.</p><p className="text-xs">Class details, discussions and student work stay private. Switching off blocks new public access; downloaded copies cannot be recalled, and an already-open PDF link can work for up to one minute.</p>{enabled!==null&&<p role="status" className="font-medium">{enabled?'Public reading enabled':'Class access required'}</p>}{error&&<p role="alert" className="text-red-700">{error}</p>}</div>}</div>;
}
