import { useCallback, useEffect, useState } from 'react';
import { executeLearningContent } from '@/services/learning-content.service';
import { syncTextFromServer } from '@/services/text.service';
import { Button } from '@/components/common/Button';
import { Markdown } from '@/components/common/Markdown';
import type { TextAnnotation } from '@/types';

interface RecordRow { id:string; kind:string; ownerId?:string; annotationId?:string; content?:string; discussed?:boolean; studentId?:string; choice?:string; groupId?:string; label?:string; memberIds?:string[]; candidateIds?:string[]; selections?:string[]; mine?:boolean; type?:string; date?:string }
interface RosterRow { id:string; name:string; thought:number; question:number; epiphany:number }
interface Snapshot { records:RecordRow[]; roster:RosterRow[]; unlocked:boolean }

export function TqeWorkspace({thoughtOnly=false,textId,classId,userId,teacher,annotations}:{thoughtOnly?:boolean;textId:string;classId:string;userId:string;teacher:boolean;annotations:TextAnnotation[]}) {
  const [data,setData]=useState<Snapshot>({records:[],roster:[],unlocked:false});
  const [error,setError]=useState('');
  const [busy,setBusy]=useState(false);
  const [tab,setTab]=useState('prepare');
  const [exit,setExit]=useState('');
  const [groupName,setGroupName]=useState('');
  const [groupMembers,setGroupMembers]=useState<string[]>([]);
  const [presenting,setPresenting]=useState(false);
  const read=useCallback(async()=>{
    const next=await executeLearningContent<Snapshot>({action:'readTqe',textId,classId});
    setData(next);
  },[textId,classId]);
  useEffect(()=>{
    let active=true;
    void executeLearningContent<Snapshot>({action:'readTqe',textId,classId}).then(next=>{if(active)setData(next);}).catch(cause=>{if(active)setError(cause.message);});
    return ()=>{active=false;};
  },[textId,classId]);
  const save=async(kind:string,values:object)=>{
    setBusy(true);setError('');
    try { await executeLearningContent({action:'saveTqe',textId,classId,kind,...values});await read(); }
    catch(cause){setError(cause instanceof Error?cause.message:'Could not save. Please retry.');}
    finally{setBusy(false);}
  };
  const refresh=async()=>{setBusy(true);setError('');try{if(!await syncTextFromServer(textId,classId))throw Error('Could not refresh annotations.');await read();}catch(cause){setError(cause instanceof Error?cause.message:'Could not refresh');}finally{setBusy(false);}};
  const roots=annotations.filter(a=>(a.kind||'annotation')==='annotation' && a.visibility!=='private' && a.moderationStatus==='visible' && a.tqeType);
  const bring=data.records.filter(r=>r.kind==='bring');
  const tables=data.records.filter(r=>r.kind==='table');
  const groups=data.records.filter(r=>r.kind==='group');
  const selectedIds=[...new Set([0,1].flatMap(rank=>groups.flatMap(g=>g.selections?.[rank]?[g.selections[rank]]:[])).concat(tables.flatMap(r=>r.annotationId?[r.annotationId]:[])))];
  const candidates=tab==='questions'?roots.filter(a=>a.tqeType==='question'):tab==='bring'?roots.filter(a=>bring.some(r=>r.annotationId===a.$id)):roots;
  const pending=annotations.some(a=>a.authorId===userId&&a.syncStatus!=='synced');
  return <section className={presenting?'fixed inset-0 z-50 overflow-auto bg-white p-8':'rounded-2xl border bg-white p-4 space-y-4'}>
    <div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-semibold">TQE · Class workspace</h2><div className="flex gap-2"><Button size="sm" variant="secondary" loading={busy} onClick={()=>void refresh()}>Refresh TQE</Button>{teacher&&<Button size="sm" variant="secondary" onClick={()=>{setPresenting(!presenting);setTab('board');}}>{presenting?'Exit presentation':'Present board'}</Button>}</div></div>
    {error&&<p role="alert" className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {!teacher&&pending&&<p className="text-sm text-amber-800">Your notes are saved on this device and waiting to sync. Refresh TQE after syncing to unlock the class workspace.</p>}
    <div className="my-3 flex flex-wrap gap-2">{(teacher?['prepare','questions','bring','roster',...(!thoughtOnly?['groups']:[]),'board']:['prepare',...(!thoughtOnly?['groups','board']:[])]).map(value=><button type="button" key={value} aria-pressed={tab===value} className={`rounded-full px-3 py-2 text-sm capitalize ${tab===value?'bg-slate-900 text-white':'bg-slate-100'}`} onClick={()=>setTab(value)}>{value==='prepare'?'My reading':value==='roster'?'Participation':value}</button>)}</div>
    {!teacher&&tab==='prepare'&&<div className="space-y-3"><p className="text-sm text-slate-600">Choose one of your notes to bring to class. Choosing another replaces your previous nomination.</p>{roots.filter(a=>a.authorId===userId).map(a=><div key={a.$id} className="rounded-xl border p-3"><Markdown content={a.content}/><label className="mt-2 flex gap-2 text-sm"><input type="checkbox" disabled={busy||a.syncStatus!=='synced'} checked={bring.some(r=>r.annotationId===a.$id)} onChange={e=>void save('bring',{annotationId:a.$id,remove:!e.target.checked})}/>Bring it</label>{data.records.filter(r=>r.kind==='nudge'&&r.annotationId===a.$id).map(r=><p key={r.id} className="mt-2 rounded-lg bg-blue-50 p-3 text-sm">Private teacher nudge: {r.content}</p>)}</div>)}<fieldset className="rounded-xl bg-slate-50 p-3"><legend className="font-medium">Three ways to show your thinking · all count equally</legend>{[['speak','Speak in the discussion'],['annotations','Show my annotations'],['conversation','Five minutes with my teacher']].map(([choice,label])=><label key={choice} className="my-2 flex gap-2 text-sm"><input type="radio" name="participation-door" disabled={busy} checked={data.records.some(r=>r.kind==='door'&&r.choice===choice)} onChange={()=>void save('door',{choice})}/>{label}</label>)}<p className="text-xs text-slate-500">Only you and your teacher can see this choice.</p></fieldset><label className="block text-sm font-medium">Which TQE changed how you read the passage?<textarea value={exit} onChange={e=>setExit(e.target.value)} className="mt-2 w-full rounded-lg border p-3" placeholder="One sentence, in your own words."/></label><Button disabled={busy||!exit.trim()} onClick={()=>void save('exit',{content:exit})}>Save exit reflection</Button>{data.records.filter(r=>r.kind==='exit').map(r=><p className="text-sm text-slate-600" key={r.id}>Saved: {r.content}</p>)}</div>}
    {teacher&&['prepare','questions','bring'].includes(tab)&&<div className="space-y-3"><p className="text-sm text-slate-600">Annotation density by paragraph · {Object.entries(roots.reduce<Record<string,number>>((counts,a)=>{counts[a.paragraphId]=(counts[a.paragraphId]||0)+1;return counts;},{})).length} passages annotated. Use Questions to find uncertainty and Bring to review nominations.</p>{candidates.map(a=><article key={a.$id} className="rounded-xl border p-3"><div className="text-xs font-semibold text-slate-500">{a.tqeType} · {roots.filter(row=>row.paragraphId===a.paragraphId).length} notes on this paragraph</div><blockquote className="my-2 border-l-2 pl-3 text-sm text-slate-600">{a.selectedText}</blockquote><Markdown content={a.content}/><div className="mt-2 flex gap-3"><Button size="sm" disabled={busy} variant="secondary" onClick={()=>void save('table',{annotationId:a.$id,remove:tables.some(r=>r.annotationId===a.$id)})}>{tables.some(r=>r.annotationId===a.$id)?'Remove from table':'Table it'}</Button><Button size="sm" disabled={busy} variant="secondary" onClick={()=>{const content=window.prompt('Private nudge — visible only to this student',data.records.find(r=>r.kind==='nudge'&&r.annotationId===a.$id)?.content||'');if(content!==null)void save('nudge',{annotationId:a.$id,content});}}>Private nudge</Button></div></article>)}</div>}
    {tab==='groups'&&(teacher||data.unlocked)?<div className="space-y-3">{teacher&&<details className="rounded-xl border p-3"><summary>Create a group</summary><input aria-label="Group name" className="my-3 w-full rounded border p-2" value={groupName} onChange={e=>setGroupName(e.target.value)} placeholder="Group name"/>{data.roster.filter(s=>!groups.some(g=>g.memberIds?.includes(s.id))).map(s=><label key={s.id} className="my-1 flex gap-2 text-sm"><input type="checkbox" checked={groupMembers.includes(s.id)} onChange={e=>setGroupMembers(ids=>e.target.checked?[...ids,s.id]:ids.filter(id=>id!==s.id))}/>{s.name}</label>)}<Button disabled={busy||!groupName.trim()||!groupMembers.length} onClick={()=>{void save('group',{groupId:crypto.randomUUID(),label:groupName,memberIds:groupMembers,selections:[]});setGroupName('');setGroupMembers([]);}}>Create group</Button></details>}{groups.map(g=><div className="rounded-xl border p-3" key={g.id}><h3 className="font-semibold">{g.label}</h3><p className="my-2 text-sm text-slate-600">Choose two, ranked. Every group’s first choice comes before second choices. For a short period, choose just one.</p>{[0,1].map(rank=><label className="my-2 block text-sm" key={rank}>Choice #{rank+1}<select className="ml-2 max-w-full rounded border p-2" disabled={busy||(!teacher&&!g.mine)} value={g.selections?.[rank]||''} onChange={e=>{const selections=[...(g.selections||[])];selections[rank]=e.target.value;void save('group',{groupId:g.groupId,label:g.label,memberIds:g.memberIds,selections:selections.filter(Boolean)});}}><option value="">Choose a TQE…</option>{roots.filter(a=>g.candidateIds?.includes(a.$id)).map(a=><option key={a.$id} value={a.$id}>{a.tqeType}: {a.content.slice(0,150)}</option>)}</select></label>)}{teacher&&<Button size="sm" variant="ghost" disabled={busy} onClick={()=>{if(window.confirm('Remove this group?'))void save('group',{groupId:g.groupId,memberIds:g.memberIds,selections:[],remove:true});}}>Remove group</Button>}</div>)}</div>:tab==='groups'&&<p className="text-sm">Post a Thought, Question, and Epiphany, then refresh to join group selection.</p>}
    {tab==='board'&&<div className="space-y-4"><p className="text-sm text-slate-500">Group first choices, then second choices and teacher additions.</p>{selectedIds.map(id=>{const a=roots.find(row=>row.$id===id),t=tables.find(row=>row.annotationId===id);if(!a)return null;return <article key={id} className="rounded-2xl border p-5"><p className="mb-2 text-xs font-semibold text-slate-500">{groups.filter(g=>g.selections?.includes(id)).map(g=>`${g.label} · #${(g.selections?.indexOf(id)||0)+1}`).join(' / ')||'Teacher addition'}{t?.discussed?' · Discussed':''}</p><Markdown content={t?.content||a.content} className={presenting?'text-3xl leading-relaxed':'text-lg'}/>{a.selectedText&&<blockquote className="mt-4 border-l-2 pl-3 text-slate-600">{a.selectedText}</blockquote>}{teacher&&<div className="mt-4 flex gap-2"><Button size="sm" variant="secondary" disabled={busy} onClick={()=>{const content=window.prompt('Edit the discussion version (original annotation stays intact)',t?.content||a.content);if(content!==null)void save('table',{annotationId:id,content,discussed:t?.discussed});}}>Edit together</Button><Button size="sm" variant="secondary" disabled={busy} onClick={()=>void save('table',{annotationId:id,content:t?.content,discussed:!t?.discussed})}>{t?.discussed?'Reopen':'Discussed'}</Button></div>}</article>;})}{!selectedIds.length&&<p className="text-slate-500">Group selections and tabled TQEs will appear here.</p>}</div>}
    {teacher&&tab==='roster'&&<div className="space-y-3"><p className="text-sm text-slate-600">Reading evidence and spoken contributions are separate. Tap T, Q, or E when you notice a contribution.</p>{data.roster.map(student=><div key={student.id} className="rounded-xl border p-3"><strong>{student.name}</strong><p className="text-sm">Reading: T {student.thought} · Q {student.question} · E {student.epiphany}{student.thought+student.question+student.epiphany===0?' · Nothing posted yet':''}</p><p className="text-xs text-slate-600">Preferred participation: {data.records.find(r=>r.kind==='door'&&r.ownerId===student.id)?.choice||'Not chosen'}</p><div className="mt-2 flex gap-2">{(['thought','question','epiphany'] as const).map(type=><Button key={type} size="sm" variant="secondary" disabled={busy} onClick={()=>void save('participation',{studentId:student.id,type,eventId:crypto.randomUUID()})}>{type[0].toUpperCase()} · {data.records.filter(r=>r.kind==='participation'&&r.studentId===student.id&&r.type===type).length}</Button>)}</div>{data.records.filter(r=>r.kind==='exit'&&r.ownerId===student.id).map(r=><p key={r.id} className="mt-2 text-sm">Exit: {r.content}</p>)}</div>)}</div>}
  </section>;
}
