import { useEffect, useState } from 'react';
import { Button } from '@/components/common/Button';
import { addCopywork, copyworkMarkdown, deleteCopywork, readCopywork } from '@/services/copywork.service';
import type { CopyworkEntry } from '@/types';
import { AssignedCopywork } from './AssignedCopywork';

export function CopyworkPanel() {
  const [entries, setEntries] = useState<CopyworkEntry[]>([]), [content, setContent] = useState(''), [sourceTitle, setSourceTitle] = useState(''), [sourceUrl, setSourceUrl] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  const [observations, setObservations] = useState<string[]>([]);
  const load = async () => { try { setEntries((await readCopywork()).entries); } catch { setMessage('Copywork could not be loaded right now.'); } };
  useEffect(() => { const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer); }, []);
  const add = async () => { if (!content.trim()) return; setBusy(true); setMessage(''); try { const { entry } = await addCopywork(content.trim(), sourceTitle.trim(), sourceUrl.trim(), observations); setEntries(old => [entry, ...old]); setContent(''); setSourceTitle(''); setSourceUrl(''); setObservations([]); setMessage('Saved with today’s date.'); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Could not save.'); } finally { setBusy(false); } };
  const markdown = () => copyworkMarkdown([...entries].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)));
  const copyAll = async () => { await navigator.clipboard.writeText(markdown()); setMessage('All copywork copied as Markdown.'); };
  const download = () => { const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([markdown()],{type:'text/markdown'}));link.download=`copywork-${new Date().toISOString().slice(0,10)}.md`;link.click();URL.revokeObjectURL(link.href); };
  return <details className="student-progress-details">
    <summary className="flex cursor-pointer list-none items-center justify-between gap-3 p-4"><span><strong className="block text-slate-950">Copywork</strong><span className="text-sm text-slate-500">Keep language worth remembering—quotes, passages, and articles.</span></span><span className="text-sm font-semibold text-slate-500">{entries.length} saved ▾</span></summary>
    <div className="space-y-4 border-t border-slate-200 p-4">
      <AssignedCopywork />
      <div><textarea className="w-full rounded-xl border border-slate-300 p-3 text-sm" rows={5} placeholder="Paste a quote, paragraph, or passage you want to keep…" value={content} onChange={e=>setContent(e.target.value)}/><div className="mt-2 grid gap-2 sm:grid-cols-2"><input className="rounded-lg border px-3 py-2 text-sm" placeholder="Source title (optional)" value={sourceTitle} onChange={e=>setSourceTitle(e.target.value)}/><input className="rounded-lg border px-3 py-2 text-sm" type="url" placeholder="Source link (optional)" value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)}/></div><fieldset className="mt-3 space-y-2" disabled={busy}><legend className="text-sm font-medium text-slate-700">Observations (optional, up to 3)</legend><p className="text-xs text-slate-500">What stands out? Notice a word choice, sentence pattern, or an idea you could try in your own writing.</p>{observations.map((value, index) => <div key={index} className="flex items-start gap-2"><label className="min-w-0 flex-1 text-xs text-slate-600">Observation {index + 1}<textarea className="mt-1 w-full rounded-lg border p-2 text-sm text-slate-900" rows={2} maxLength={2000} value={value} onChange={e => setObservations(old => old.map((item, i) => i === index ? e.target.value : item))}/></label><button type="button" aria-label={'Remove observation ' + (index + 1)} className="mt-5 rounded p-2 text-slate-500" onClick={() => setObservations(old => old.filter((_, i) => i !== index))}>×</button></div>)}{observations.length < 3 && <button type="button" className="text-sm font-medium text-blue-700" onClick={() => setObservations(old => [...old, ''])}>+ Add observation</button>}</fieldset><Button className="mt-2" loading={busy} disabled={!content.trim()} onClick={()=>void add()}>Save copywork</Button></div>
      {message&&<p className="text-sm text-slate-600" role="status">{message}</p>}
      {entries.length>0&&<><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={()=>void copyAll()}>Copy all</Button><Button size="sm" variant="secondary" onClick={download}>Export Markdown</Button></div><div className="max-h-96 space-y-3 overflow-auto">{entries.map(entry=><article key={entry.$id} className="rounded-xl bg-slate-50 p-3"><div className="flex items-start justify-between gap-3"><time className="text-xs font-semibold text-slate-500">{new Date(entry.createdAt).toLocaleString()}</time><button className="text-xs text-red-600" onClick={()=>void deleteCopywork(entry.$id).then(()=>setEntries(old=>old.filter(item=>item.$id!==entry.$id)))}>Delete</button></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-800">{entry.content}</p>{entry.sourceTitle&&(entry.sourceUrl?<a className="mt-2 inline-block text-xs font-semibold text-blue-700" href={entry.sourceUrl} target="_blank" rel="noreferrer">{entry.sourceTitle} ↗</a>:<p className="mt-2 text-xs italic text-slate-500">— {entry.sourceTitle}</p>)}{Boolean(entry.observations?.length) && <section className="mt-3 border-t border-slate-200 pt-2"><h3 className="text-xs font-semibold text-slate-600">My observations</h3><ol className="mt-1 list-decimal space-y-1 pl-5 text-sm text-slate-800">{entry.observations!.map((observation, index) => <li key={index} className="whitespace-pre-wrap">{observation}</li>)}</ol></section>}</article>)}</div></>}
    </div>
  </details>;
}
