Config.history.maxStates=1;Config.history.controls=false;Config.saves.isAllowed=()=>false;Config.ui.stowBarInitially=true;Config.passages.nobr=true;
setup.attemptId=parent===window?crypto.randomUUID():'standalone';setup.choices=[];setup.driverAttempts=[];setup.journal={};setup.drafts={};setup.channel=null;setup.ready=false;setup.booted=false;setup.accepted=false;
Config.navigation.override=destination=>setup.ready?destination:'Start';
setup.send=(type,extra={})=>{if(parent!==window&&setup.channel)parent.postMessage({protocol:'episode-v1',episode:setup.story.id,version:setup.story.version,channel:setup.channel,type,choices:setup.choices.slice(),driverAttempts:setup.driverAttempts.map(v=>v.slice()),journal:{...setup.journal},...extra},location.origin);};
setup.refresh=()=>Engine.play(!setup.accepted?'Start':setup.choices.length===setup.scenes.length?(setup.assessDriver(setup.driverAttempts).passed?'Assessment':'Driver'):setup.choices.length?'Consequence'+setup.choices.length:'Decision1');
window.addEventListener('message',event=>{const m=event.data;if(event.origin!==location.origin||event.source!==parent||m?.protocol!=='episode-v1'||m.type!=='init'||m.episode!==setup.story.id||m.version!==setup.story.version||typeof m.channel!=='string')return;if(setup.ready){if(setup.booted){if(State.passage==='Start')setup.refresh();setup.send('started');}return;}try{setup.assess(m.choices);setup.assessDriver(m.driverAttempts||[]);validateJournal(m.journal,m.choices,setup.scenes.length);}catch{return;}setup.attemptId=typeof m.attemptId==='string'?m.attemptId:'standalone';setup.channel=m.channel;setup.choices=m.choices.slice();setup.journal={...m.journal};setup.drafts={...m.journalDraft};setup.accepted=setup.choices.length>0;setup.driverAttempts=(m.driverAttempts||[]).map(v=>v.slice());setup.ready=true;if(setup.booted){setup.refresh();setup.send('started');}});
const paragraph=(target,text)=>{const p=document.createElement('p');p.textContent=text;target.append(p);return p;};
const asset=n=>'../../question-journal/v1/'+n;
Macro.add('ownChoice',{handler(){const [id,label]=this.args,step=setup.choices.length,b=document.createElement('button');b.className='stone-choice';b.textContent=label;b.onclick=()=>{if(b.disabled||setup.choices.length!==step)return;b.disabled=true;const input=document.getElementById('journal-entry');if(input){if(step===0)setup.journal.question=input.value;else if(step===setup.scenes.length-1)setup.journal.reflection=input.value;}setup.choices.push(id);setup.send('save');Engine.play('Consequence'+(step+1));};this.output.append(b);}});
Macro.add('ownPersonal',{handler(){const key=this.args[0],label=document.createElement('label'),input=document.createElement('textarea');input.id='journal-entry';input.rows=3;input.maxLength=1000;label.htmlFor=input.id;label.textContent=key==='question'?'My own question (optional)':'What I discovered; what remains uncertain (optional)';input.value=setup.drafts[key]||setup.journal[key]||'';input.oninput=()=>{setup.drafts[key]=input.value;setup.send('draft',{field:key,text:input.value});};this.output.append(label,input);paragraph(this.output,'This private line is saved when I choose below. It earns no correctness points and does not generate a bespoke answer.');}});
Macro.add('ownConsequence',{handler(){const i=Number(this.args[0]),c=setup.scenes[i].choices.find(c=>c.id===setup.choices[i]);paragraph(this.output,c.response);if(i===0&&setup.journal.question)paragraph(this.output,'My personal question: '+setup.journal.question);}});
Macro.add('ownSource',{handler(){const ids=this.args.length?this.args:setup.sources.map(s=>s.id);for(const id of ids){const s=setup.sources.find(s=>s.id===id);if(!s)continue;const d=document.createElement('details');d.open=true;const title=document.createElement('summary');title.textContent='Source card · '+s.title;d.append(title);const q=document.createElement('blockquote');q.textContent=s.quote;d.append(q);paragraph(d,'Exact excerpt · Don Quixote '+setup.story.chapter+' · John Ormsby translation (1885)');paragraph(d,s.note);const a=document.createElement('a');a.href=s.url;a.target='_blank';a.rel='noopener';a.textContent='Read the full source chapter';d.append(a);this.output.append(d);}}});
Macro.add('ownStats',{handler(){const s=setup.assess(setup.choices),box=document.createElement('div');box.className='stone-stats';notebookDomains.forEach((name,i)=>{const cell=document.createElement('div'),label=document.createElement('span'),n=document.createElement('strong');label.textContent=name;n.textContent=s.scores[i]+'/25';cell.append(label,n);box.append(cell);});this.output.append(box);const d=document.createElement('details');d.innerHTML='<summary>My notebook rubric</summary><p>Four explicit checkpoints, each worth 25. Supported observation and reasoning earn 25; an unsupported overclaim earns 5; not yet demonstrated earns 0. Two distinct supported answers are available at every checkpoint. Question selection, character approval, and persuasion earn no correctness points. This private episode score is not a posted course grade.</p>';this.output.append(d);}});
Macro.add('ownStage',{handler(){const i=Number(this.args[0]),s=setup.scenes[i],stage=document.createElement('div');stage.className='stage';stage.style.backgroundImage='url("'+asset('landscape.webp')+'")';stage.setAttribute('role','group');stage.setAttribute('aria-label','La Mancha: courtyard, road, and distant windmills');if(s.speaker==='journal'){const door=document.createElement('div');door.className='journal-door';door.textContent='The Question Journal';const mark=document.createElement('span');mark.textContent='♧';door.append(mark);stage.append(door);}else{const figure=document.createElement('figure'),sprite=document.createElement('div'),caption=document.createElement('figcaption');figure.className='character speaking';sprite.className='sprite';sprite.style.backgroundImage='url("'+asset(s.speaker+'.webp')+'")';const mood=setup.story.id==='the-giants-have-sails'&&i>=4?'troubled':'neutral';sprite.style.backgroundPosition=mood==='troubled'?'100% 0':'0% 0';sprite.setAttribute('role','img');sprite.setAttribute('aria-label',setup.characters[s.speaker]+' · '+mood);caption.textContent=setup.characters[s.speaker]+' · '+mood;figure.append(sprite,caption);stage.append(figure);}this.output.append(stage);}});
Macro.add('ownMargin',{handler(){const margin=setup.scenes[Number(this.args[0])].margin;if(!margin)return;const inset=document.createElement('aside');inset.className='cervantes-margin';inset.setAttribute('aria-label','Cervantes at the edge of the page');const img=document.createElement('div');img.className='margin-portrait';img.style.backgroundImage='url("'+asset('cervantes.webp')+'")';img.setAttribute('role','img');img.setAttribute('aria-label','Cervantes peeking into the margin');inset.append(img);paragraph(inset,margin.text);margin.followups.forEach(f=>{const d=document.createElement('details'),sum=document.createElement('summary');sum.textContent=f.q;d.append(sum);paragraph(d,f.a);inset.append(d);});this.output.append(inset);}});
Macro.add('ownExplore',{handler(){const scene=setup.scenes[Number(this.args[0])];if(scene.kind!=='question')return;const heading=document.createElement('h2');heading.textContent='Keep asking, or continue';this.output.append(heading);scene.choices.filter(c=>c.id!==setup.choices[Number(this.args[0])]).forEach(c=>{const d=document.createElement('details'),summary=document.createElement('summary');summary.textContent=c.label;d.append(summary);paragraph(d,c.response);this.output.append(d);});}});
Macro.add('ownDriver',{handler(){const root=this.output,heading=document.createElement('h1');heading.textContent='The journal’s return page';root.append(heading);paragraph(root,'The door appears again on the cover. The journal asks four questions. Three correct open it. If I miss the threshold, I review and try again; my choices and personal writing remain safe.');const previous=setup.assessDriver(setup.driverAttempts);if(setup.driverAttempts.length){paragraph(root,'Last check: '+previous.score+'/4. My notebook and route are preserved.');const answers=setup.driverAttempts.at(-1);setup.driverQuestions.forEach((q,i)=>{if(answers[i]!==q.answer)paragraph(root,'Review '+(i+1)+': '+q.note);});}const form=document.createElement('form');root.append(form);setup.driverQuestions.forEach((q,i)=>{const group=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=(i+1)+'. '+q.prompt;group.append(legend);q.options.forEach((text,n)=>{const label=document.createElement('label'),input=document.createElement('input');input.type='radio';input.name='fare-'+i;input.value=n;input.required=true;label.append(input,document.createTextNode(' '+text));group.append(label);});form.append(group);});const button=document.createElement('button');button.type='submit';button.textContent='Open the return door';form.append(button);form.onsubmit=event=>{event.preventDefault();if(!form.reportValidity())return;button.disabled=true;setup.driverAttempts.push(setup.driverQuestions.map((_,i)=>Number(new FormData(form).get('fare-'+i))));setup.send('save');setup.refresh();};const review=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Review the source cards';review.append(summary);new Wikifier(review,'<<ownSource>>');root.append(review);}});
Macro.add('ownAssessment',{handler(){const a=setup.assess(setup.choices);paragraph(this.output,'The journal records what I discovered and leaves a space for what remains uncertain. The return door opens. I step through alone, back into the classroom. Mr. Hepting looks up. “Find anything?” I have more than an answer now: I have a better question.');a.ending.paragraphs.forEach(p=>paragraph(this.output,p));paragraph(this.output,'My first commitment: '+setup.scenes[3].choices.find(c=>c.id===setup.choices[3]).label);paragraph(this.output,'My opening question: '+setup.scenes[0].choices.find(c=>c.id===setup.choices[0]).label);if(setup.journal.question)paragraph(this.output,'My personal question: '+setup.journal.question);if(setup.journal.reflection)paragraph(this.output,'My reflection: '+setup.journal.reflection);paragraph(this.output,a.total+'/100 · Notebook learning');notebookDomains.forEach((n,i)=>paragraph(this.output,n+': '+a.scores[i]+'/25'));const d=document.createElement('details'),sum=document.createElement('summary');sum.textContent='See the evidence behind my score';d.append(sum);setup.choices.forEach((id,i)=>{const scene=setup.scenes[i],c=scene.choices.find(c=>c.id===id);if(scene.kind!=='checkpoint')return;paragraph(d,scene.title+' — '+c.label);paragraph(d,c.response+' Points: '+c.points.join(' / '));});this.output.append(d);paragraph(this.output,'Carry into class: choose one specific detail, explain what it supports, then name something it does not establish. My next encounter starts fresh, regardless of this score or the knight’s approval.');setup.send('complete');}});
// Passage-local pacing never changes the immutable choice history or score.
setup.cancelReveal=()=>{};
$(document).on(':passageinit',()=>setup.cancelReveal());
$(document).on(':passagedisplay',function(){
 const passage=document.querySelector('.passage'),beats=passage.querySelector('.story-beats'),after=passage.querySelector('.after-beats');
 if(beats&&after){
  const paragraphs=Array.from(beats.children);const full=document.createElement('div');full.className='sr-only';full.innerHTML=beats.innerHTML;beats.before(full);beats.setAttribute('aria-hidden','true');let index=0,timer=null,finish=()=>{};
  const controls=document.createElement('div');controls.className='beat-controls';
  const next=document.createElement('button'),all=document.createElement('button'),counter=document.createElement('span');
  next.textContent='Next ▸';all.textContent='Show all';all.className='quiet';counter.className='beat-count';
  controls.append(counter,next,all);beats.after(controls);after.hidden=true;
  const stop=()=>{if(timer)clearInterval(timer);timer=null;};setup.cancelReveal=stop;
  const show=()=>{
   stop();paragraphs.forEach((p,i)=>p.hidden=i!==index);const p=paragraphs[index];
   counter.textContent=(index+1)+' / '+paragraphs.length;next.textContent=index===paragraphs.length-1?'Continue ▸':'Next ▸';
   // Keep full accessible text; the optional visual reveal never delays screen readers.
   const original=p.innerHTML;finish=()=>{stop();p.innerHTML=original;};
   if(!matchMedia('(prefers-reduced-motion: reduce)').matches){
    const accessible=document.createElement('span');accessible.className='sr-only';accessible.innerHTML=original;
    const visual=document.createElement('span');visual.setAttribute('aria-hidden','true');visual.innerHTML=original;
    p.replaceChildren(accessible,visual);const walker=document.createTreeWalker(visual,NodeFilter.SHOW_TEXT),nodes=[];let node;
    while((node=walker.nextNode()))nodes.push({node,text:node.textContent});nodes.forEach(n=>n.node.textContent='');
    let n=0,c=0;timer=setInterval(()=>{for(let j=0;j<3&&n<nodes.length;j++){const entry=nodes[n];entry.node.textContent=entry.text.slice(0,++c);if(c>=entry.text.length){n++;c=0;}}if(n===nodes.length)finish();},16);
   }
  };
  const unlock=(showAll=false)=>{finish();if(showAll)paragraphs.forEach(p=>p.hidden=false);else{const recall=document.createElement('details');recall.innerHTML='<summary>Recall the conversation</summary>'+paragraphs.map(p=>'<p>'+p.innerHTML+'</p>').join('');after.prepend(recall);}controls.remove();after.hidden=false;const target=after.querySelector('summary,button');target?.focus({preventScroll:true});};
  next.addEventListener('click',()=>{if(timer){finish();return;}if(index<paragraphs.length-1){index++;show();}else unlock();});
  all.addEventListener('click',()=>unlock(true));show();
 }
 const h=passage.querySelector('h1');if(h){h.setAttribute('tabindex','-1');h.focus({preventScroll:true});}window.scrollTo(0,0);
});

$(document).one(':storyready',()=>{setup.booted=true;if(setup.channel){setup.refresh();setup.send('started');}if(parent===window){setup.ready=true;setup.refresh();return;}parent.postMessage({protocol:'episode-v1',episode:setup.story.id,version:setup.story.version,type:'ready'},location.origin);});
