import { Modal } from '@/components/common/Modal';
import { Markdown } from '@/components/common/Markdown';
import { projectCardMaterials } from '@/services/planner-editor';
import type { WeeklyPlanData } from '@/services/planner.service';
import { plannerLabel } from '@/services/planner-layout';

export function PlannerSharePreview({data,busy,error,onClose,onConfirm}:{data:WeeklyPlanData;busy:boolean;error:string;onClose:()=>void;onConfirm:()=>void}) {
  const projected=projectCardMaterials(data);
  const mapped=projected.courses.filter(course=>projected.lessons.some(lesson=>lesson.classCode===course.classCode&&lesson.classId));
  const hasContent=mapped.some(course=>data.publishAgenda||course.presentations.some(item=>item.publish)||course.texts.some(item=>item.publish&&item.url));
  return <Modal open onClose={()=>{if(!busy)onClose();}} title="Share with students" panelClassName="sm:max-w-3xl"><div className="space-y-4 text-sm"><p>These items become visible <strong>immediately when you confirm</strong>, grouped under the dates shown. This is not a scheduled release.</p><p className="rounded-lg bg-emerald-50 p-3">Private intentions, preparation tasks, progress checks, and lesson notes are not shared. Cards excluded from sharing are not included below.</p>{mapped.map(course=>{
    const lessons=projected.lessons.filter(row=>row.classCode===course.classCode);
    const texts=course.texts.filter(item=>item.publish),presentations=course.presentations.filter(item=>item.publish);
    return <section key={course.classCode} className="rounded-xl border p-3"><h3 className="font-semibold">{lessons[0]?.classLabel||plannerLabel[course.classCode]}</h3>{data.publishAgenda&&<details className="mt-2"><summary className="cursor-pointer font-medium">Weekly agenda · {data.week.startDate}</summary><div className="mt-2 space-y-3">{texts.length>0&&<div><h4 className="font-medium">Texts</h4>{texts.map((item,index)=><p key={index}>{item.title} — {item.date}</p>)}</div>}{presentations.length>0&&<div><h4 className="font-medium">Presentations</h4>{presentations.map((item,index)=><p key={index}>{item.title}</p>)}</div>}{lessons.map(lesson=><div key={lesson.id}><h4 className="font-medium">{lesson.date}</h4>{lesson.slots?.filter(slot=>!slot.optional&&slot.publish!==false).map(slot=><Markdown key={slot.id} content={`- **${slot.title}:** ${slot.content||''}${/^https?:\/\//.test(slot.url||'')?` [Open](${slot.url})`:''}`}/>)}{lesson.reminders.length>0&&<Markdown content={`- **Remember:** ${lesson.reminders.join(' · ')}`}/>}</div>)}</div></details>}<h4 className="mt-3 font-medium">Separate class materials</h4>{texts.filter(item=>item.url).map((item,index)=><p key={'t'+index} className="mt-1 rounded bg-blue-50 p-2">Text: {item.title} · {item.date}<span className="block break-all text-xs">{item.url}</span></p>)}{presentations.map((item,index)=><p key={'p'+index} className="mt-1 rounded bg-purple-50 p-2">Presentation: {item.title} · {item.date}{item.url&&<span className="block break-all text-xs">{item.url}</span>}</p>)}{texts.some(item=>!item.url)&&<p className="mt-2 text-xs text-amber-800">Texts without links appear only in the agenda, if included; no separate reading will be created.</p>}{!data.publishAgenda&&!presentations.length&&!texts.some(item=>item.url)&&<p className="text-slate-500">Nothing selected for this class.</p>}</section>;
  })}{projected.courses.length>mapped.length&&<p className="text-amber-800">Unmapped courses are skipped. Map their classes before sharing.</p>}<p className="text-xs text-slate-500">Sharing again updates planner-created items. Previously shared items are not deleted when unchecked; remove them from the class if needed. Friday vocabulary and copywork releases are managed separately under Units.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="flex gap-2"><button className="rounded-lg border px-3 py-2" disabled={busy} onClick={onClose}>Back to planning</button><button className="rounded-lg bg-blue-600 px-3 py-2 text-white disabled:opacity-40" disabled={busy||!hasContent} onClick={onConfirm}>{busy?'Sharing…':'Confirm · Share now'}</button></div></div></Modal>;
}
