import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button } from '@/components/common/Button';
import { controlLivePresentation, readLivePresentation, submitLiveAnswer, type LivePresentationState } from '@/services/presentation.service';

const BAR_COLORS = ['bg-blue-500', 'bg-emerald-500', 'bg-amber-500', 'bg-fuchsia-500'];

export function LivePresentationPage() {
  const { sessionId } = useParams<{ sessionId: string }>();
  const [state, setState] = useState<LivePresentationState | null>(null);
  const [answer, setAnswer] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [filter, setFilter] = useState('');
  const [selectedResponse, setSelectedResponse] = useState('');
  const activeQuestionId = useRef('');
  const refresh = useCallback(async () => { if (!sessionId) return; try { const next = await readLivePresentation(sessionId); const nextId = next.activeQuestion?.id || ''; if (nextId !== activeQuestionId.current) { activeQuestionId.current = nextId; setAnswer(''); setSelectedResponse(''); } setState(next); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not load the presentation.'); } }, [sessionId]);
  useEffect(() => { const initial = window.setTimeout(() => void refresh(), 0); const timer = window.setInterval(() => void refresh(), 1200); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, [refresh]);
  const responses = useMemo(() => (state?.responses || []).filter(item => item.answer.toLowerCase().includes(filter.toLowerCase())), [state?.responses, filter]);
  const command = async (value: 'next' | 'previous' | 'pause' | 'reveal' | 'hide' | 'end') => { if (!sessionId) return; setBusy(true); await controlLivePresentation(sessionId, value); await refresh(); setBusy(false); };
  const submit = useCallback(async (value = answer) => { if (!sessionId || !value.trim()) return; setBusy(true); setError(''); try { await submitLiveAnswer(sessionId, value); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not submit your answer.'); } finally { setBusy(false); } }, [answer, refresh, sessionId]);
  useEffect(() => { const handleKey = (event: KeyboardEvent) => { if (state?.isTeacher || state?.ownAnswer !== null || state?.activeQuestion?.type !== 'mc' || busy) return; const index = Number(event.key) - 1; if (index >= 0 && index < state.activeQuestion.options.length) void submit(String(index)); }; window.addEventListener('keydown', handleKey); return () => window.removeEventListener('keydown', handleKey); }, [state, busy, submit]);
  if (!state) return <main className="flex min-h-screen items-center justify-center bg-gray-950 p-6 text-white">{error || 'Joining presentation…'}</main>;
  const question = state.activeQuestion;
  if (state.isTeacher) return <main className="min-h-screen bg-gray-100 p-4 sm:p-6"><div className="mx-auto max-w-6xl space-y-4"><header className="flex flex-wrap items-center justify-between gap-3"><div><Link to={`/classes/${state.session.classId}`} className="text-sm text-gray-500">← Class</Link><h1 className="text-2xl font-bold">{state.session.title}</h1></div><div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={busy} onClick={() => void command('previous')}>Previous</Button><Button variant="secondary" disabled={!question || busy} onClick={() => void command('pause')}>Dark screen</Button><Button disabled={busy} onClick={() => void command('next')}>Next</Button><Button variant="secondary" disabled={!question || busy} onClick={() => void command(state.reveal ? 'hide' : 'reveal')}>{state.reveal ? 'Hide answer' : 'Reveal answer'}</Button><Button variant="danger" disabled={busy} onClick={() => window.confirm('End this live presentation?') && void command('end')}>End</Button></div></header>{question ? <><section className="rounded-2xl bg-gray-950 p-6 text-white sm:p-10"><p className="text-sm text-gray-400">Question {question.sortOrder + 1} of {state.questions.length}</p><h2 className="mt-3 text-3xl font-bold leading-tight sm:text-5xl">{question.text}</h2>{state.reveal && question.answer && <p className="mt-6 rounded-xl bg-white/10 p-4 text-xl">Answer: {question.answer}</p>}<p className="mt-6 text-lg text-gray-300">{state.answeredCount} of {state.enrolledCount} students answered</p></section>{question.type === 'mc' ? <ResponseBars options={question.options} counts={state.mcCounts} /> : <section className="grid gap-4 lg:grid-cols-[20rem_1fr]"><div className="rounded-2xl bg-white p-4"><input className="mb-3 w-full rounded-lg border px-3 py-2" placeholder="Filter responses…" value={filter} onChange={event => setFilter(event.target.value)}/><div className="max-h-[28rem] space-y-2 overflow-auto">{responses.map(item => <button key={item.id} className="w-full rounded-lg border p-3 text-left hover:bg-gray-50" onClick={() => setSelectedResponse(item.answer)}><strong className="block text-xs text-gray-500">{item.label}</strong><span className="line-clamp-2 text-sm">{item.answer}</span></button>)}</div></div><div className="flex min-h-72 items-center justify-center rounded-2xl bg-white p-8 text-center"><p className="whitespace-pre-wrap text-2xl leading-relaxed sm:text-4xl">{selectedResponse || 'Select an anonymous response to present it.'}</p></div></section>}</> : <section className="flex min-h-[60vh] items-center justify-center rounded-2xl bg-gray-950 p-8 text-center text-white"><div><h2 className="text-4xl font-bold">Students are ready</h2><p className="mt-3 text-gray-400">Click Next to show the next question.</p></div></section>}</div></main>;
  if (!question || state.session.status !== 'active') return <main className="flex min-h-screen items-center justify-center bg-gray-950 p-8 text-center text-white"><div><div className="mx-auto mb-5 h-3 w-3 animate-pulse rounded-full bg-white"/><h1 className="text-3xl font-bold">Waiting for the next question</h1><p className="mt-3 text-gray-400">Keep this screen open.</p></div></main>;
  return <main className="min-h-screen bg-gray-950 p-4 text-white sm:p-8"><div className="mx-auto max-w-3xl"><p className="text-sm text-gray-400">Question {question.sortOrder + 1}</p><h1 className="mt-3 text-3xl font-bold leading-tight sm:text-5xl">{question.text}</h1>{state.ownAnswer !== null ? <div className="mt-8 space-y-5"><p className="rounded-xl bg-white/10 p-4">Your answer: {question.type === 'mc' ? question.options[Number(state.ownAnswer)] : state.ownAnswer}</p>{question.type === 'mc' && <ResponseBars options={question.options} counts={state.mcCounts} dark />}{state.reveal && question.answer && <p className="rounded-xl bg-emerald-900 p-4">Answer: {question.answer}</p>}<p className="text-center text-gray-400">Waiting for the teacher…</p></div> : <div className="mt-8">{question.type === 'mc' ? <div className="grid gap-3 sm:grid-cols-2">{question.options.map((option, index) => <button key={index} disabled={busy} onClick={() => void submit(String(index))} className="min-h-20 rounded-xl border border-gray-600 bg-gray-900 p-4 text-left text-lg hover:border-white"><strong className="mr-3">{index + 1}</strong>{option}</button>)}</div> : question.type === 'paragraph' ? <textarea autoFocus rows={9} className="w-full rounded-xl bg-white p-4 text-gray-950" placeholder="Write your response…" value={answer} onChange={event => setAnswer(event.target.value)}/> : <input autoFocus className="w-full rounded-xl bg-white p-4 text-lg text-gray-950" placeholder={question.type === 'cloze' ? 'Fill in the blank…' : 'Type your answer…'} value={answer} onChange={event => setAnswer(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') void submit(); }}/>} {question.type !== 'mc' && <Button className="mt-4 w-full" size="lg" loading={busy} disabled={!answer.trim()} onClick={() => void submit()}>Submit answer</Button>}</div>}{error && <p className="mt-4 text-red-300">{error}</p>}</div></main>;
}

function ResponseBars({ options, counts, dark = false }: { options: string[]; counts: number[]; dark?: boolean }) {
  const total = counts.reduce((sum, count) => sum + count, 0);
  return <section className={`space-y-3 rounded-2xl p-5 ${dark ? 'bg-gray-900' : 'bg-white'}`}>{options.map((option, index) => { const percent = total ? Math.round(((counts[index] || 0) / total) * 100) : 0; return <div key={index}><div className="mb-1 flex justify-between gap-3 text-sm"><span><strong>{index + 1}.</strong> {option}</span><span>{counts[index] || 0} · {percent}%</span></div><div className={`h-5 overflow-hidden rounded-full ${dark ? 'bg-gray-700' : 'bg-gray-100'}`}><div className={`h-full transition-all ${BAR_COLORS[index % BAR_COLORS.length]}`} style={{ width: `${percent}%` }}/></div></div>; })}</section>;
}
