import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/common/Button';
import { Modal } from '@/components/common/Modal';
import { db } from '@/db/schema';
import { executeLearningContent } from '@/services/learning-content.service';
import { useAuth } from '@/contexts/AuthContext';
import { useLiveQuery } from 'dexie-react-hooks';
import { readPlanner } from '@/services/planner.service';
import type { PlannerWeekSource } from '@/services/planner-parser';
import { blankResource, importPlanningBrief, importVocabulary, readUnits, saveUnit, unpackUnit, precedingFriday, type PlanningRelease, type UnitPlan, type UnitResource, type ResourceKind } from '@/services/unit-planning';

const input = 'mt-1 w-full rounded-lg border border-slate-300 bg-white p-2 text-sm text-slate-900';
export function PlanningUnitsPage() {
  const { user } = useAuth();
  const classes=useLiveQuery(()=>user?db.classes.where('teacherId').equals(user.$id).toArray():[],[user?.$id]);
  const [units,setUnits]=useState<UnitPlan[]>([]),[weeks,setWeeks]=useState<PlannerWeekSource[]>([]),[selected,setSelected]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<UnitResource|null>(null);
  const [filter,setFilter]=useState('all');
  const [mapping,setMapping]=useState<Record<string,string>>({});
  const [consolidation,setConsolidation]=useState<{decks:string[];core:number;reference:number;skipped:string[]}|null>(null);
  const [releases,setReleases]=useState<PlanningRelease[]>([]);
  useEffect(()=>{void Promise.all([readUnits(),readPlanner()]).then(([result,planner])=>{setUnits(result.units.map(unpackUnit));setReleases(result.releases||[]);const source=planner.sources.find(item=>item.active);setWeeks(source?JSON.parse(source.parsedJson).weeks:[]);setMapping(source?JSON.parse(source.mappingJson||'{}'):{});setSelected(result.units[0]?.$id||'');}).catch(cause=>setMessage(cause.message));},[]);
  const unit=units.find(item=>item.id===selected);
  const update=(change:Partial<UnitPlan>)=>setUnits(current=>current.map(item=>item.id===selected?{...item,...change}:item));
  const save=async()=>{if(!unit)return;setBusy(true);setMessage('');try{await saveUnit(unit);setReleases((await readUnits()).releases);setMessage('Unit saved. Approved releases are scheduled; overdue releases will run on the next server tick.');}catch(cause){setMessage(cause instanceof Error?cause.message:'Could not save');}finally{setBusy(false);}};
  const importFile=async(file?:File)=>{if(!file)return;try{const content=await file.text();const next:UnitPlan[]=(file.name.endsWith('.json')||file.name.endsWith('.local'))?JSON.parse(content).units:file.name.endsWith('.txt')?importPlanningBrief(content,units,weeks):importVocabulary(content,weeks,units);setUnits(next.map(item=>({...item,classIds:item.classIds.length?item.classIds:Object.entries(mapping).filter(([code,id])=>id&&(code===item.course||(item.course==='WL'&&code.startsWith('WL-')))).map(([,id])=>id)})));setSelected(next[0]?.id||'');setMessage(`Loaded ${next.reduce((sum,item)=>sum+item.cards.length,0)} cards for review. Map classes, approve the vocabulary schedule, and save each unit.`);}catch(cause){setMessage(cause instanceof Error?cause.message:'Import failed');}};
  const saveAll=async()=>{setBusy(true);let saved=0;try{for(const item of units){await saveUnit(item);saved++;}setReleases((await readUnits()).releases);setMessage(`Saved ${saved} units and their approved schedules.`);}catch(cause){setMessage(`Saved ${saved} units before an error: ${cause instanceof Error?cause.message:'Save failed'}. You can retry safely.`);}finally{setBusy(false);}};
  const unitWeeks=unit?weeks.filter(week=>week.startDate>=unit.startDate&&week.startDate<=unit.endDate):[];
  const vocabularyWeeks=unit?[...new Set(unit.cards.map(card=>card.week).filter(Boolean))].sort():[];
  const choices=[...new Set([...unitWeeks.map(week=>week.startDate),...vocabularyWeeks])].sort();
  return <main className="mx-auto max-w-6xl space-y-5 p-4 sm:p-6">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold">Planning</h1><p className="text-sm text-slate-500">Build your unit bank, then arrange each week.</p></div><Link to="/planner" className="rounded-lg border px-4 py-2">Weeks →</Link></header>
    {message&&<p role="status" className="rounded-xl bg-blue-50 p-3 text-sm text-blue-900">{message}</p>}
    <div className="flex flex-wrap gap-2"><label className="cursor-pointer rounded-lg border bg-white px-4 py-2 text-sm">Import vocabulary / planning brief<input type="file" accept=".csv,.txt,.json,.local" className="hidden" onChange={event=>void importFile(event.target.files?.[0])}/></label><Button variant="secondary" onClick={()=>{const next:UnitPlan={id:crypto.randomUUID(),course:'WL',number:'1',title:'New unit',startDate:weeks[0]?.startDate||new Date().toISOString().slice(0,10),endDate:weeks[0]?.startDate||'',knowledge:'',skills:'',essentialQuestion:'',classIds:[],cards:[],resources:[],vocabularyApproved:false};setUnits(current=>[...current,next]);setSelected(next.id);}}>New unit</Button><Link to="/planner" className="p-2 text-sm text-blue-700">Annual calendar and class mapping</Link></div>
    {units.length>0&&<div className="flex flex-wrap items-center gap-3"><label className="text-sm"><input type="checkbox" checked={units.every(item=>item.vocabularyApproved)} onChange={e=>setUnits(current=>current.map(item=>({...item,vocabularyApproved:e.target.checked})))}/>Approve all vocabulary schedules</label><Button variant="secondary" loading={busy} onClick={()=>void saveAll()}>Save all units</Button></div>}
    <select aria-label="Unit" className={input} value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Choose a unit</option>{units.map(item=><option key={item.id} value={item.id}>{item.course} · {item.title}</option>)}</select>
    {unit&&<>
      <section className="space-y-3 rounded-2xl border bg-white p-4"><div className="grid gap-3 sm:grid-cols-3"><label>Title<input className={input} value={unit.title} onChange={e=>update({title:e.target.value})}/></label><label>Starts<input type="date" className={input} value={unit.startDate} onChange={e=>update({startDate:e.target.value})}/></label><label>Ends<input type="date" className={input} value={unit.endDate} onChange={e=>update({endDate:e.target.value})}/></label></div><label className="block">Course<select className={input} value={unit.course} onChange={e=>update({course:e.target.value,vocabularyApproved:false})}><option>WL</option><option>AP</option><option>ETH</option></select></label><fieldset><legend className="text-sm font-semibold">Classes sharing this unit and its vocabulary</legend><div className="mt-2 flex flex-wrap gap-4">{classes?.map(cls=><label key={cls.$id} className="text-sm"><input type="checkbox" checked={unit.classIds.includes(cls.$id)} onChange={e=>update({classIds:e.target.checked?[...unit.classIds,cls.$id]:unit.classIds.filter(id=>id!==cls.$id)})}/> {cls.courseName} · {cls.name}</label>)}</div></fieldset><label className="block">Essential question<input className={input} value={unit.essentialQuestion} onChange={e=>update({essentialQuestion:e.target.value})}/></label><div className="grid gap-3 sm:grid-cols-2"><label>Knowledge targets<textarea className={input} rows={3} value={unit.knowledge} onChange={e=>update({knowledge:e.target.value})}/></label><label>Skills targets<textarea className={input} rows={3} value={unit.skills} onChange={e=>update({skills:e.target.value})}/></label></div></section>
      <section className="rounded-2xl border bg-white p-4"><h2 className="font-semibold">Vocabulary · {unit.cards.length} cards</h2><p className="mt-1 text-sm text-slate-500">Core: preceding Friday, 8 a.m. China time. Reference: unit start. Each course has two cumulative decks.</p><label className="my-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={unit.vocabularyApproved} onChange={e=>update({vocabularyApproved:e.target.checked})}/>Approve this vocabulary release schedule</label>{[...vocabularyWeeks,''].map(week=>{const cards=unit.cards.filter(card=>card.week===week);return cards.length?<details key={week} className="border-t py-2"><summary className="cursor-pointer text-sm font-semibold">{week?`Week of ${week}`:'Unit reference'} · {cards.length} cards {week&&<span className="font-normal text-slate-500">· releases {new Date(precedingFriday(week)).toLocaleString('en-GB',{timeZone:'Asia/Shanghai'})}</span>}</summary><div className="mt-2 space-y-2">{cards.map(card=><div key={card.id} className="rounded-lg bg-slate-50 p-2 text-sm"><strong>{card.front}</strong> <span className="text-xs text-slate-500">{card.kind} · {card.tier}</span><p>{card.back}</p></div>)}</div></details>:null;})}</section>
      <section className="rounded-2xl border bg-white p-4"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">Unit resource bank</h2><Button size="sm" onClick={()=>setEditing(blankResource())}>Add resource</Button></div><select aria-label="Resource type filter" className={input} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All resources</option>{['presentation','text','activity','copywork','quiz','assignment'].map(kind=><option key={kind}>{kind}</option>)}</select><div className="mt-3 grid gap-2 sm:grid-cols-2">{unit.resources.filter(resource=>filter==='all'||resource.kind===filter).map(resource=><article key={resource.id} className="rounded-xl border p-3"><span className="text-xs font-semibold uppercase text-blue-700">{resource.kind} · {resource.week||'Unscheduled'}</span><h3 className="font-medium">{resource.title}</h3><p className="line-clamp-2 text-sm text-slate-500">{resource.content}</p>{resource.kind==='copywork'&&<p className="text-xs text-slate-500">{resource.paragraphs} paragraphs · {resource.approved?'Approved for Friday release':'Draft'} · Due {resource.date||'not set'}</p>}<div className="mt-2 flex gap-3"><button className="text-sm text-blue-700" onClick={()=>setEditing(structuredClone(resource))}>✎ Edit</button><button className="text-sm text-red-700" onClick={()=>{if(window.confirm(`Remove ${resource.title} from the unit bank? Saved lesson copies remain.`))update({resources:unit.resources.filter(item=>item.id!==resource.id)});}}>Remove</button></div></article>)}</div></section>
      <section className="rounded-xl border p-3"><h2 className="font-semibold">Release status</h2><p className="text-xs text-slate-500">Scheduled server runs every 15 minutes, including Friday at 8 a.m. China time.</p>{releases.filter(item=>item.unitId===unit.id).map(item=><p key={item.$id} className="mt-1 text-sm">{new Date(item.releaseAt).toLocaleString('en-GB',{timeZone:'Asia/Shanghai'})} · {item.status==='done'?'Released':item.status==='failed'?`Needs attention: ${item.lastError}`:'Scheduled'}</p>)}</section><div className="flex flex-wrap gap-3"><Button loading={busy} onClick={()=>void save()}>Save unit and schedules</Button><Button variant="secondary" disabled={busy} onClick={()=>void executeLearningContent<{decks:string[];core:number;reference:number;skipped:string[]}>({action:'consolidatePlanningDecks',unitId:unit.id}).then(setConsolidation).catch(cause=>setMessage(cause.message))}>Combine existing class decks…</Button></div>
    </>}
    {consolidation&&unit&&<Modal open title="Combine existing decks" onClose={()=>setConsolidation(null)}><p className="text-sm">Move {consolidation.core} existing cards into Core Vocabulary and {consolidation.reference} into Reference Vocabulary. Card IDs and review histories are preserved. Source decks are archived and removed from these classes.</p><p className="mt-2 text-sm">{consolidation.decks.join(' · ')||'No eligible legacy decks'}</p>{consolidation.skipped.length>0&&<p className="mt-2 text-sm text-amber-800">Shared with other classes or owned by another teacher—left in place: {consolidation.skipped.join(' · ')}</p>}<Button className="mt-4" loading={busy} disabled={!consolidation.decks.length} onClick={async()=>{setBusy(true);try{await executeLearningContent({action:'consolidatePlanningDecks',unitId:unit.id,apply:true});setConsolidation(null);setMessage('Decks combined. Refresh class materials to see the cumulative decks.');}catch(cause){setMessage(cause instanceof Error?cause.message:'Consolidation failed; retry to resume.');}finally{setBusy(false);}}}>Combine and preserve progress</Button></Modal>}
    {editing&&unit&&<Modal open title="Resource" onClose={()=>setEditing(null)}><div className="space-y-3"><label className="block">Type<select className={input} value={editing.kind} onChange={e=>setEditing({...editing,kind:e.target.value as ResourceKind})}>{['presentation','text','activity','copywork','quiz','assignment'].map(kind=><option key={kind}>{kind}</option>)}</select></label><label className="block">Title<input className={input} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label className="block">Passage / instructions<textarea className={input} rows={4} value={editing.content} onChange={e=>setEditing({...editing,content:e.target.value})}/></label><label className="block">Link<input type="url" className={input} value={editing.url} onChange={e=>setEditing({...editing,url:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><label>Suggested week<select className={input} value={editing.week} onChange={e=>setEditing({...editing,week:e.target.value})}><option value="">Unscheduled</option>{choices.map(week=><option key={week}>{week}</option>)}</select></label><label>Lesson / due date<input type="date" className={input} value={editing.date} onChange={e=>setEditing({...editing,date:e.target.value})}/></label><label>Minutes<input type="number" min={0} max={180} className={input} value={editing.minutes} onChange={e=>setEditing({...editing,minutes:Math.max(0,Number(e.target.value))})}/></label>{editing.kind==='copywork'&&<label>Paragraphs<input type="number" min={1} className={input} value={editing.paragraphs} onChange={e=>setEditing({...editing,paragraphs:Math.max(1,Number(e.target.value))})}/></label>}</div><label className="block">Skills addressed<input className={input} value={editing.skills} onChange={e=>setEditing({...editing,skills:e.target.value})}/></label><details><summary>Vocabulary addressed ({editing.targets.length})</summary><div className="mt-2 max-h-40 overflow-auto">{unit.cards.map(card=><label key={card.id} className="block text-sm"><input type="checkbox" checked={editing.targets.includes(card.id)} onChange={e=>setEditing({...editing,targets:e.target.checked?[...editing.targets,card.id]:editing.targets.filter(id=>id!==card.id)})}/> {card.front}</label>)}</div></details><label className="flex gap-2"><input type="checkbox" checked={editing.optional} onChange={e=>setEditing({...editing,optional:e.target.checked})}/>If time / reserve</label>{['copywork','text','presentation'].includes(editing.kind)&&<label className="flex gap-2"><input type="checkbox" checked={editing.approved} onChange={e=>setEditing({...editing,approved:e.target.checked})}/>{editing.kind==='copywork'?'Approve student link for Friday release':'Include when publishing the weekly plan'}</label>}<Button disabled={!editing.title.trim()} onClick={()=>{update({resources:[...unit.resources.filter(item=>item.id!==editing.id),editing]});setEditing(null);}}>Keep resource</Button></div></Modal>}
  </main>;
}
