import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {useAuth} from '@/contexts/AuthContext';
import {db} from '@/db/schema';
import PortfolioEditor from '@/components/ethics/PortfolioEditor';
import {exportEntries,localEntries,newEntry,readPortfolio,setPortfolioStage,syncPortfolio,type Entry,type PortfolioData} from '@/services/ethics-portfolio.service';
import {STONE_CLASS_ID} from '@/services/stone.service';
export default function PrinciplesPortfolioPage(){const {user}=useAuth(),{classId=''}=useParams();return user?<Portfolio key={user.$id+classId} userId={user.$id} role={user.role} classId={classId}/>:null;}
function Portfolio({userId,role,classId}:{userId:string;role:string;classId:string}){
 const [entries,setEntries]=useState<Entry[]>([]),[editor,setEditor]=useState<Entry|null>(null),[teacher,setTeacher]=useState(false),[allowed,setAllowed]=useState(false),[status,setStatus]=useState('Checking access…'),[settings,setSettings]=useState<PortfolioData['settings']>({open:false,deadline:null}),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string[]>([]),[deadline,setDeadline]=useState('');
 const refresh=async()=>{setBusy(true);try{await syncPortfolio(userId,classId);const data=await readPortfolio(userId,classId);setTeacher(data.teacher);setSettings(data.settings);setEntries(data.teacher?data.entries:await localEntries(userId,classId));setStatus('Account entries updated.');}catch(e){setStatus('Showing this device’s saved entries. '+(e instanceof Error?e.message:''));}finally{setBusy(false);}};
 useEffect(()=>{let active=true;void(async()=>{if(classId!==STONE_CLASS_ID){setStatus('This portfolio is for Ethics and Leadership.');return;}const cls=await db.classes.get(classId),members=await db.class_members.where('[classId+userId]').equals([classId,userId]).toArray();const ownTeacher=cls?.teacherId===userId&&['teacher','admin'].includes(role);if(!ownTeacher&&!(role==='student'&&members.some(m=>m.role==='student'&&(!m.expiresAt||Date.parse(m.expiresAt)>Date.now())))){if(active)setStatus('Class membership required.');return;}if(!active)return;setAllowed(true);setTeacher(ownTeacher);setEntries(await localEntries(userId,classId));await refresh();})();return()=>{active=false;};},[userId,classId]);
 const stage=async(open:boolean)=>{setBusy(true);try{const result=await setPortfolioStage(classId,open,deadline?new Date(deadline).toISOString():null);setSettings(result.settings);setStatus(open?'Reconsideration opened. Students can refresh their discussion stage.':'Reconsideration closed. Existing writing is preserved.');}catch(e){setStatus(e instanceof Error?e.message:'Could not change stage.');}finally{setBusy(false);}};
 return <main className="mx-auto max-w-4xl space-y-5 p-4 sm:p-6"><Link className="text-teal-900 underline" to={`/classes/${classId}/game`}>← The Game</Link><h1 className="text-3xl font-bold">Principles Portfolio</h1><p>Ideas under examination · Start with an episode or a reading. Connect your entries over time to develop a question or principle for a larger paper.</p><p role="status" className="text-sm">{status}</p>{allowed&&<><button className="rounded-lg border px-4 py-3" disabled={busy} onClick={()=>void refresh()}>Refresh saved portfolio</button>{teacher?<section className="space-y-3 rounded-xl border bg-teal-50 p-5"><h2 className="font-semibold">Post-discussion reconsideration</h2><p>Applies to this class’s portfolio entries. Allow 3–5 minutes after discussion. Students keep, clarify, or change their judgment with reasons.</p><p>Current stage: {settings.open?'Open':'Closed'}{settings.deadline?` · until ${new Date(settings.deadline).toLocaleString()}`:''}</p><label className="block">Optional deadline (your local time)<input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)} className="ml-2 rounded border p-2"/></label><div className="flex flex-wrap gap-3"><button disabled={busy} className="rounded-lg bg-teal-900 px-4 py-3 text-white" onClick={()=>void stage(true)}>Open / reopen reconsideration</button><button disabled={busy} className="rounded-lg border px-4 py-3" onClick={()=>void stage(false)}>Close reconsideration</button></div></section>:<button className="rounded-lg bg-teal-900 px-4 py-3 font-semibold text-white" onClick={()=>setEditor(newEntry(userId,classId,{kind:'reading',title:'',url:'',passage:''}))}>Start from a reading</button>}
 {editor&&<PortfolioEditor key={editor.key} initial={editor} onSaved={()=>void refresh()}/>}
 <section className="space-y-3"><h2 className="text-xl font-semibold">{teacher?'Class entries · private teacher view':'Your entries'}</h2><p className="text-sm">{teacher?'Assess the reasoning, not the ending or a changed opinion.':'Choose related entries to export for your next synthesis. Your originals and reconsiderations stay together.'}</p>{!entries.length&&<p>No entries yet. Complete the Egypt episode or start with a reading.</p>}{entries.map(e=><article className="rounded-xl border p-4" key={e.userId+e.id}><div className="flex items-start gap-3"><input aria-label={`Select ${e.source.title||'entry'} for export`} type="checkbox" checked={selected.includes(e.userId+e.id)} onChange={ev=>setSelected(s=>ev.target.checked?[...s,e.userId+e.id]:s.filter(k=>k!==e.userId+e.id))}/><div className="min-w-0 flex-1"><h3 className="font-semibold">{e.source.title||'Reading draft'}</h3><p className="text-sm">{teacher?`${e.studentName||'Student'} · `:''}{e.source.kind==='episode'?'Episode':'Reading'} · {e.submitted?'Original submitted':'Draft'} · {e.reconsideredAt?'Reconsideration saved':'Reconsideration not yet submitted'}{e.preview?' · preview':''}</p>{teacher?<details className="mt-3"><summary>Read entry</summary>{e.answers.map((a,i)=><p key={i} className="my-3 whitespace-pre-wrap"><strong>{i+1}.</strong> {a}</p>)}<p className="whitespace-pre-wrap"><strong>Reconsideration:</strong> {e.reconsideration||'Not yet added'}</p></details>:<button className="mt-3 rounded border px-3 py-2" onClick={()=>setEditor(e)}>Open entry</button>}</div></div></article>)}<button disabled={!selected.length} className="rounded-lg border px-4 py-3 disabled:opacity-50" onClick={()=>exportEntries(entries.filter(e=>selected.includes(e.userId+e.id)))}>Export selected entries</button></section></>}</main>;
}
