import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useLiveQuery } from 'dexie-react-hooks';
import { db } from '@/db/schema'; import { useAuth } from '@/contexts/AuthContext'; import { Card } from '@/components/common/Card'; import { Button } from '@/components/common/Button';
import { addAnnotation, ANNOTATIONS_TO_UNLOCK, canSeePeerAnnotations } from '@/services/text.service';

export function TextReaderPage(){ const {textId}=useParams(); const {user,isTeacher,isParent}=useAuth(); const [drafts,setDrafts]=useState<Record<string,string>>({}); const [types,setTypes]=useState<Record<string,'observation'|'question'>>({});
 const text=useLiveQuery(()=>textId?db.texts.get(textId):undefined,[textId]); const paragraphs=useLiveQuery(()=>textId?db.text_paragraphs.where('textId').equals(textId).sortBy('sortOrder'):[],[textId]);
 const classId=useLiveQuery(async()=>{if(!textId||!user)return '';const assigned=await db.text_assignments.where('textId').equals(textId).toArray();if(isTeacher)return assigned[0]?.classId||'';const mine=await db.class_members.where('userId').equals(user.$id).toArray();return assigned.find(a=>mine.some(m=>m.classId===a.classId))?.classId||''},[textId,user?.$id,isTeacher]);
 const annotations=useLiveQuery(async()=>{if(!textId||!classId||!user)return [];const all=await db.text_annotations.where('[textId+classId]').equals([textId,classId]).toArray();const unlocked=isTeacher||isParent||await canSeePeerAnnotations(textId,classId,user.$id);return all.filter(a=>a.moderationStatus==='visible'&&(unlocked||a.authorId===user.$id));},[textId,classId,user?.$id,isTeacher,isParent]);
 const mine=annotations?.filter(a=>a.authorId===user?.$id).length||0; if(!text||!user)return <div className="p-6 text-gray-400">Loading…</div>;
 return <div className="p-4 max-w-3xl mx-auto space-y-5"><header><Link to="/texts" className="text-sm text-blue-600">← Texts</Link><h1 className="text-2xl font-bold mt-2">{text.title}</h1><p className="text-gray-500">{text.author}</p>{text.contentMode!=='link'&&!isTeacher&&!isParent&&mine<ANNOTATIONS_TO_UNLOCK&&<p className="mt-2 text-sm rounded bg-blue-50 p-2">Add {ANNOTATIONS_TO_UNLOCK-mine} more observation{ANNOTATIONS_TO_UNLOCK-mine===1?'':'s'} or question{ANNOTATIONS_TO_UNLOCK-mine===1?'':'s'} to reveal classmates’ notes.</p>}</header>
 {text.contentMode==='link'&&text.externalUrl&&<Card className="text-center space-y-3"><p className="text-gray-600">This reading is hosted on another website.</p><a href={text.externalUrl} target="_blank" rel="noreferrer"><Button>Open reading ↗</Button></a></Card>}
 {paragraphs?.map((p,i)=><Card key={p.$id} className="space-y-3"><p className="text-xs text-gray-400">Paragraph {i+1}</p><p className="whitespace-pre-wrap leading-7">{p.content}</p>{annotations?.filter(a=>a.paragraphId===p.$id).map(a=><div key={a.$id} className="rounded bg-gray-50 p-2 text-sm"><b>{a.type==='question'?'Question':'Observation'} · {a.authorId===user.$id?'You':a.anonymousLabel}</b><p>{a.content}</p></div>)}{!isTeacher&&!isParent&&<div className="flex gap-2"><select className="border rounded px-2 text-sm" value={types[p.$id]||'observation'} onChange={e=>setTypes({...types,[p.$id]:e.target.value as 'observation'|'question'})}><option value="observation">Observation</option><option value="question">Question</option></select><input className="flex-1 border rounded px-2 text-sm" value={drafts[p.$id]||''} onChange={e=>setDrafts({...drafts,[p.$id]:e.target.value})}/><Button size="sm" disabled={!drafts[p.$id]?.trim()} onClick={()=>void addAnnotation({textId:text.$id,paragraphId:p.$id,classId:classId||'',authorId:user.$id,type:types[p.$id]||'observation',content:drafts[p.$id]||''}).then(()=>setDrafts({...drafts,[p.$id]:''}))}>Add</Button></div>}</Card>)}
 <Link to="/discussions" className="inline-block text-blue-600 font-medium">Continue in Discussions →</Link></div>;
}
