import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {scenes,characters} from '../functions/learning-content/src/young-content.js';
const read=p=>readFileSync(p,'utf8'),sha=s=>createHash('sha256').update(s).digest('hex');
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
let twee=':: StoryTitle\nThe Ride That Wouldn’t Autocorrect\n\n:: StoryData\n{"ifid":"6516CEB6-C959-4715-8E66-8BB47A65B7E4","format":"SugarCube","format-version":"2.37.3","start":"Start"}\n\n:: StoryScript [script]\n'+read('functions/learning-content/src/young-content.js').replaceAll('export ','')+'\nsetup.driverQuestions=driverQuestions;setup.assessDriver=assessDriver;setup.scenes=scenes;setup.characters=characters;setup.assess=assessYoung;setup.sources=sourceNotes;setup.sourceUrl=sourceUrl;setup.prompt=assignmentPrompt;\n'+read('stories/own-english/story.js')+'\n\n:: StoryStylesheet [stylesheet]\n'+read('stories/own-english/story.css')+'\n\n:: Start\n<div class="eyebrow">AP Language · A fictional author encounter</div><h1>The Ride That Wouldn’t Autocorrect</h1><p>A hidden WeChat mini-program. One magazine deadline. More than one way to be heard.</p><p>10 decisions · 12–15 minutes plus writing · No timer · Unlimited replays</p><p>The classroom encounter, dialogue, people and outcomes are invented. Only labelled excerpts are Young’s actual words. This story complements the assigned reading.</p><<if window.parent === window>><<button "Begin standalone preview">><<run setup.ready=true;setup.refresh()>><</button>><<else>><p>Connecting to your class…</p><</if>>\n';
scenes.forEach((s,i)=>{
 const stage=`<aside class="scene-side"><<ownStage ${i}>><<ownStats>><div class="charge">Decision ${i+1} of 10</div></aside>`;
 twee+=`\n:: Decision${i+1}\n<div class="novel">${stage}<section class="dialogue"><div class="eyebrow">The Ride That Wouldn’t Autocorrect</div><h1>${escape(s.title)}</h1><p class="speaker">${characters[s.speaker]}</p><div class="story-beats">${s.text.map(t=>'<p>'+escape(t)+'</p>').join('')}</div><div class="after-beats">${s.source?'<<ownSource "'+s.source+'">>':''}${i===7?'<<ownComputer>>':''}<div class="choice-heading">Your next move</div>${s.choices.map(c=>'<<ownChoice '+JSON.stringify(c.id)+' '+JSON.stringify(c.label)+'>>').join('\n')}</div></section></div>\n`;
 twee+=`\n:: Consequence${i+1}\n<div class="novel"><aside class="scene-side"><<ownStage ${i} true>><<ownStats>></aside><section class="dialogue"><h1>${escape(s.title)}</h1><div class="story-beats"><<ownConsequence ${i}>></div><div class="after-beats">${i>=3&&i<=5?'<<ownQuestionSource '+i+'>>':''}<<button "Continue">><<goto "${i===9?'Driver':'Decision'+(i+2)}">><</button>></div></section></div>\n`;
});
twee+='\n:: Driver\n<<ownDriver>>\n\n:: Assessment\n<div class="eyebrow">An opportunity is not the end of a story</div><h1>What your choices leave open</h1><<ownAssessment>><details><summary>Recall all source cards</summary><<ownSource>></details><details><summary>Questions you did not choose</summary>';
scenes.slice(3,6).forEach(s=>s.choices.forEach(c=>{twee+='<h3>'+escape(c.label)+'</h3><p>'+escape(c.response)+'</p>';}));
twee+='</details><<button "Replay with a different approach">><<if window.parent === window>><<run setup.choices=[];setup.driverAttempts=[];setup.refresh()>><<else>><<run setup.send("replay")>><</if>><</button>><<button "Return to The Game">><<run setup.send("exit")>><</button>><details><summary>Sources and fiction</summary><p>Core text: Vershawn Ashanti Young, “Should Writers Use They Own English?”, Iowa Journal of Cultural Studies 12 (2010), 110–118. Full article linked on every source card. Read the entire assigned essay; cards are short excerpts and reading guides. Checked October 9, 2026. No generated answer represents Young’s personal view. The AI uses the essay cards and Young’s first-person faculty statement, not an invented corpus of other writings. Episode concepts: objection, concession, qualification, audience, code-meshing, evidence. These are not presented as the weekly vocabulary list.</p></details>\n';
const source='stories/own-english/episode.twee',html='public/stories/own-english/v1/index.html',manifest='stories/own-english/build.json';
if(process.argv.includes('--check')){const m=JSON.parse(read(manifest));if(read(source)!==twee||m.sourceSha256!==sha(twee)||m.htmlSha256!==sha(read(html)))throw new Error('Young episode is stale');console.log('Young source and HTML match');}
else{writeFileSync(source,twee);execFileSync(process.env.TWEEGO||'tweego',['-f','sugarcube-2','-o',html,source],{env:{...process.env,TWEEGO_PATH:process.cwd()+'/vendor/twine'},stdio:'inherit'});writeFileSync(manifest,JSON.stringify({tweego:'2.1.1',sugarcube:'2.37.3',sourceSha256:sha(twee),htmlSha256:sha(read(html))},null,2)+'\n');}
