import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {decisionSource,entryKey,exportEntries,newEntry,portfolioDb,queueEntry,readPortfolio,saveDraft,syncPortfolio,textOnly,type Entry,type PortfolioData} from '@/services/ethics-portfolio.service';
import type {StoneAttempt} from '@/services/stone.service';
import egypt from '../../../functions/learning-content/src/ethics-egypt-context.json';
const prompts={episode:[['Which choice deserves a closer look?','Describe one decision you faced and what you chose. What belief, rule, or priority could justify that choice?'],['What is the strongest reason for your choice—and the strongest reason against it?','Refer to specific details of the situation. Consider what you knew at the time and who would bear the consequences.'],['What do you think should be done now?','Defend your original choice, revise it, or explain why you remain uncertain. What circumstance would make a different choice justified?']],reading:[['What idea here deserves examination?','Identify a claim, rule, judgment, or assumption. Anchor it in a short quotation or specific detail, and explain it in your own words.'],['What is the strongest reason to accept it—and what makes it difficult to accept?','Use the text and discussion. Distinguish reasons the text gives from reasons you are proposing.'],['Where do you stand for now, and why?','Defend, qualify, reject, or leave the idea unresolved. Explain what your judgment depends on.']]};
const field='mt-2 block w-full rounded-lg border border-stone-300 bg-white p-3 text-gray-900 disabled:bg-stone-100';
export default function PortfolioEditor({initial,attempt,onSaved}:{initial:Entry;attempt?:StoneAttempt;onSaved?:()=>void}){
 const [entry,setEntry]=useState(initial),[status,setStatus]=useState('Drafts save on this device.'),[busy,setBusy]=useState(false),[settings,setSettings]=useState<PortfolioData['settings']>({open:!!initial.preview,deadline:null});
 const changed=useRef(false),latest=useRef(entry);latest.current=entry;
 const persist=useRef(Promise.resolve());
 const update=(patch:Partial<Entry>)=>{changed.current=true;const next={...latest.current,...patch};latest.current=next;setEntry(next);persist.current=persist.current.then(()=>saveDraft(next)).then(()=>setStatus('Draft saved on this device.')).catch(()=>setStatus('Could not save on this device. Export your writing before leaving.'));};
 useEffect(()=>{if(initial.preview)return;let active=true;const load=async()=>{try{await syncPortfolio(initial.userId,initial.classId);const data=await readPortfolio(initial.userId,initial.classId);if(active){setSettings(data.settings);const remote=await portfolioDb.entries.get(initial.key);if(remote&&!changed.current)setEntry(remote);setStatus('Account connected. Drafts save on this device until you submit.');}}catch(e){if(active)setStatus('Account unavailable; your draft stays on this device. '+(e instanceof Error?e.message:''));}};void load();window.addEventListener('online',load);return()=>{active=false;window.removeEventListener('online',load);};},[initial.key]);
 const refreshStage=async()=>{try{const data=await readPortfolio(entry.userId,entry.classId);setSettings(data.settings);setStatus('Discussion stage refreshed.');}catch{setStatus('Could not refresh the discussion stage. Please try again when connected.');}};
 const submit=async(reconsider=false)=>{setBusy(true);try{await persist.current;const next=await queueEntry({...latest.current,submitted:true,submittedAt:entry.submittedAt||new Date().toISOString(),...(reconsider?{reconsideredAt:new Date().toISOString()}: {})});changed.current=false;latest.current=next;setEntry(next);setStatus(next.preview?'Preview saved on this device; not a student submission.':'Saved on this device; syncing…');if(!next.preview){await syncPortfolio(next.userId,next.classId);setStatus('Saved to your account. Private to you and your teacher.');}onSaved?.();}catch(e){setStatus('Your writing is retained on this device. '+(e instanceof Error?e.message:'Sync pending.'));}finally{setBusy(false);}};
 const open=entry.preview||(settings.open&&(!settings.deadline||Date.parse(settings.deadline)>Date.now()));
 const source=entry.source;
 return <section className="space-y-5 rounded-2xl border border-teal-200 bg-[#f6f4eb] p-4 sm:p-6" aria-label="Ideas under examination">
  <header><p className="text-xs uppercase tracking-widest text-teal-800">Principles Portfolio</p><h2 className="mt-2 text-2xl font-semibold">Ideas under examination</h2><p className="mt-2">Choose a moment worth thinking about. Your reasons matter more than the ending or score. You can also begin with a class reading.</p><p className="mt-2 text-sm text-gray-600">One entry, about 150–250 words altogether. Private to you and your teacher. {entry.preview?'This is a local teacher preview.':''}</p></header>
  {!entry.submitted&&<fieldset disabled={busy}><legend className="font-semibold">Start with</legend><div className="mt-2 flex flex-wrap gap-4">{attempt&&<label><input type="radio" name={`source-${entry.id}`} checked={source.kind==='episode'} onChange={()=>update({source:decisionSource(attempt,0)})}/> An episode decision</label>}<label><input type="radio" name={`source-${entry.id}`} checked={source.kind==='reading'} onChange={()=>update({source:{kind:'reading',title:'',url:'',passage:''}})}/> A class reading</label></div></fieldset>}
  {source.kind==='episode'?<div className="space-y-3"><label className="block font-medium">Decision to examine<select className={field} disabled={entry.submitted||busy||!attempt} value={source.index} onChange={e=>attempt&&update({source:decisionSource(attempt,Number(e.target.value))})}>{egypt.scenes.map((s,i)=><option key={i} value={i}>{i+1}. {s.title}</option>)}</select></label><p><strong>You chose:</strong> {source.label}</p><details className="rounded-lg bg-white p-3"><summary className="cursor-pointer font-medium">Recall the situation and its outcome</summary><p className="mt-3 whitespace-pre-wrap">{textOnly(source.passage||'')}</p><p className="mt-3"><strong>Optional conversation:</strong> {textOnly(source.aside||'')}</p><p className="mt-3 font-semibold">Options at the time</p><ul className="list-disc pl-5">{source.options?.map(([id,label])=><li key={id}>{label}</li>)}</ul><p className="mt-3"><strong>What happened next:</strong> {source.outcome}</p><p className="mt-3 text-sm">Judge the decision using what you knew then, as well as what the outcome helps you notice. Curiosity or experimenting with a branch need not express your beliefs.</p></details></div>:<fieldset disabled={entry.submitted||busy} className="space-y-3"><label className="block font-medium">Reading title<input maxLength={255} className={field} value={source.title} onChange={e=>update({source:{...source,title:e.target.value}})}/></label><label className="block font-medium">Reading or discussion link (optional)<input type="url" maxLength={2048} className={field} value={source.url} onChange={e=>update({source:{...source,url:e.target.value}})}/></label><label className="block font-medium">Quotation or specific passage reference<textarea maxLength={6000} className={field} value={source.passage} onChange={e=>update({source:{...source,passage:e.target.value}})}/></label></fieldset>}
  {prompts[source.kind].map(([title,hint],i)=><label key={i} className="block font-semibold">{i+1}. {title}<span className="mt-1 block text-sm font-normal text-gray-600">{hint}</span><textarea rows={4} maxLength={6000} readOnly={entry.submitted} disabled={busy} className={field+' font-normal'} value={entry.answers[i]} onChange={e=>update({answers:entry.answers.map((v,j)=>i===j?e.target.value:v)})}/></label>)}
  {!entry.submitted&&<details><summary className="cursor-pointer text-sm font-medium">A little help getting started</summary><p className="mt-2 text-sm">“A reason to accept this is…” · “This becomes difficult when…” · “For now, I think… because…”</p><p className="mt-2 text-sm">You may start from a class idea; credit its contributor and develop your own reasons. For a further challenge, identify an assumption or explain exactly when your principle applies.</p></details>}
  {!entry.submitted?<button className="rounded-lg bg-teal-900 px-5 py-3 font-semibold text-white disabled:opacity-50" disabled={busy||entry.answers.some(a=>!a.trim())||(source.kind==='reading'&&(!source.title.trim()||!source.passage.trim()))} onClick={()=>void submit()}>Save original response</button>:<div className="space-y-3 border-t border-stone-300 pt-4"><h3 className="text-lg font-semibold">After our discussion</h3><p>Your original response is preserved above. Take 3–5 minutes to keep, clarify, or change your judgment. Explain what in the reading or discussion supports your decision. If you remain unsure, name the difficulty.</p><p className="text-sm">Keeping a well-supported judgment is as valuable as changing it. Two or three sentences are enough.</p><label className="block font-medium">My reconsideration<textarea maxLength={6000} rows={4} className={field} disabled={!open||busy} value={entry.reconsideration} onChange={e=>update({reconsideration:e.target.value})}/></label>{!open&&<p className="text-sm">Your teacher will open this stage after discussion. Refresh when invited.</p>}{settings.deadline&&<p className="text-sm">Deadline: {new Date(settings.deadline).toLocaleString()}</p>}<div className="flex flex-wrap gap-3"><button className="rounded-lg bg-teal-900 px-4 py-3 font-semibold text-white disabled:opacity-50" disabled={!open||busy||!entry.reconsideration.trim()} onClick={()=>void submit(true)}>Save reconsideration</button>{!entry.preview&&<button className="rounded-lg border px-4 py-3" onClick={()=>void refreshStage()}>Refresh discussion stage</button>}</div></div>}
  <p role="status" className="text-sm text-gray-700">{status}</p><div className="flex flex-wrap items-center gap-4"><button className="rounded-lg border px-4 py-2 text-sm" onClick={()=>exportEntries([entry])}>Export this entry</button><Link className="text-sm font-semibold text-teal-900 underline" to={`/classes/${entry.classId}/principles`}>Open Principles Portfolio</Link></div>
 </section>;
}
export function EpisodeReflection({attempt}:{attempt:StoneAttempt}){
 const [entry,setEntry]=useState<Entry|null>(null);
 useEffect(()=>{let active=true;void(async()=>{const key=entryKey(attempt.userId,attempt.classId,attempt.attemptId);const existing=await portfolioDb.entries.get(key);const next=existing||{...newEntry(attempt.userId,attempt.classId,decisionSource(attempt,0),attempt.preview),id:attempt.attemptId,key};if(active)setEntry(next);})();return()=>{active=false;};},[attempt.attemptId]);
 return entry?<PortfolioEditor key={entry.key} initial={entry} attempt={attempt}/>:<p>Opening reflection…</p>;
}
