// Immutable source/rubric bundle for own-english v1. Dialogue is fictional unless labelled quotation.
export const YOUNG_ID='own-english';
export const YOUNG_VERSION=1;
export const sourceUrl='https://artsci.tamu.edu/english/_files/_documents/research/use-they-own.pdf';
export const sourceNotes=[
 {id:'A',title:'Attitudes and prejudice',quote:'But dont nobody’s language, dialect, or style make them “vulnerable to prejudice.” It’s ATTITUDES.',note:'Young relocates the cause of linguistic discrimination from a speaker’s dialect to powerful listeners’ attitudes.'},
 {id:'B',title:'A proposal, not only a rejection',quote:'Code meshing is the new code switching',note:'Young proposes blending dialects and languages within communication. His essay performs that practice. He opposes requiring home and school varieties to stay separate.'},
 {id:'C',title:'Objection and response',note:'Near the end, Young imagines an objection that his examples do not belong in scholarship, then points to academic writers and his own essay. He follows another objection about earning permission with a response about blended writing’s legitimacy.'},
 {id:'D',title:'Craft still matters',note:'The conclusion includes instruction in punctuation, meaning, word choice, sentence structures, and some standard English. Code-meshing is not a demand to stop learning writing craft.'},
 {id:'E',title:'Beyond the essay · Young’s faculty statement',url:'https://uwaterloo.ca/english/profiles/vershawn-young',note:'In his first-person faculty biography, Young describes code-meshing as enabling minoritized language users to blend cultural and heritage languages in academic, professional, and public communication. He also describes work as a teacher, principal, performer, and diversity consultant. This statement supports the breadth of his educational purpose; it does not predict his answer to every contemporary dilemma.'}
];
export const assignmentPrompt='Write 150–250 words advising Lin and magazine editor Mei. Explain how Young answers an objection in one specific passage, then develop your own recommendation. Represent Mei’s accessibility concern fairly, support your reasoning with precise textual details, and explain what your proposal gains and what difficulty remains. Agreement with Young is not required. Use the linked full article to extend beyond the source cards.';
export const rubric=['Rhetorical situation: audience, purpose, context and constraints (25).','Claims and evidence: accurate, relevant support and fair representation (25).','Reasoning and organization: explanation, qualification and answering objections while advancing a claim (25).','Style: purposeful, clear expression and rhetorical choices, without requiring one dialect (25).'];
export const characters={lin:'Lin · student writer',jordan:'Jordan · visiting student',mei:'Mei · magazine editor',young:'Young · fictionalized encounter'};
// Points are pedagogical evidence, separate from narrative indicator changes and publication outcome.
const c=(id,label,response,points,reactions=['neutral','neutral'],delta=[0,0,0,0])=>({id,label,response,points,reactions,delta});
export const scenes=[
 {title:'The ride that wouldn’t autocorrect',background:'classroom',cast:['lin','mei'],speaker:'lin',text:[
 'Mr. Hepting opens WeChat, taps a mini-program hidden behind an extremely ordinary dumpling icon, and orders a DiDi. “Field trip. Bring an objection.” Outside, a small car unfolds into a classroom-sized cabin. The driver declines to explain the geometry.',
 'Lin shows you a message from the school magazine: “Your argument about belonging is strong. We can publish it Friday if you remove the home-language expressions. Some readers may not understand them.” Mei has a deadline and a real concern about readers. Lin wants the byline—but wants to recognize the voice beneath it.',
 'Lin has asked you to be a writing partner. You can advise; the final submission remains Lin’s decision. The car’s destination changes to a lecture by Vershawn Ashanti Young. Before you arrive, what do you promise?'],
 choices:[c('reach','Help Lin reach the magazine’s readers, while checking each proposed edit.','Lin wants the opportunity. Mei is relieved you will work with her. You have promised careful revision, not a blank cheque to erase the voice.',[3,0,0,2],['happy','happy'],[5,0,0,0]),c('voice','Help Lin preserve the voice, while looking for ways to orient unfamiliar readers.','Lin relaxes. Mei still needs a plan for readers who cannot follow a phrase. You have promised both ownership and work.',[3,0,0,2],['happy','sad'],[0,0,0,5]),c('decide','Promise to persuade Lin to reject every change before seeing the edits.','Lin pauses: “Even if an edit helps me say what I mean?” Mei closes the document for now. Your promise has arrived before your evidence.',[0,0,0,0],['sad','sad'],[-3,-4,0,0])]},
 {title:'The seat beside you',background:'hall',cast:['jordan','lin'],speaker:'jordan',text:[
 'A visiting student moves a bag so you can sit down. “I’m Jordan. I been working on our zine all week. Folks keep fixing the voice and leaving the weak evidence. That part needs work too.”',
 'Jordan points to an unsupported claim in a draft. You understand the concern about evidence, but “zine” is unfamiliar. Lin looks from Jordan’s marked-up page to the magazine message.'],
 choices:[c('clarify','“What kind of publication is your zine? And what evidence would strengthen this claim?”','“Small independent magazine,” Jordan explains, then shows a source. Asking about one unfamiliar term kept the idea at the centre. Lin starts comparing the drafts.',[3,3,0,2],['happy','happy'],[8,3,0,2]),c('engage','“You’re separating voice from support. Show me the claim you think needs evidence.”','Jordan points to the missing support. You have followed the main point. You can still ask about the publication later; understanding need not mean pretending to know every word.',[3,3,0,2],['happy','neutral'],[6,3,0,2]),c('correct','“You mean ‘I have been.’ You’ll sound more credible if you fix that first.”','“You understood me,” Jordan says. “Do you want to talk about the evidence?” Lin stops taking notes. Jordan is a person with useful knowledge, not a test of your grammar.',[0,0,0,0],['sad','sad'],[-3,-6,-2,-3])]},
 {title:'What the room hears',background:'hall',cast:['young','jordan'],speaker:'young',source:'A',text:[
 'Young places a short quotation from the essay on the screen. Read source card A below. In our imagined lecture, he asks: “Where does this sentence put the cause of harm? What changes when we move the cause?” The printed excerpt is the evidence; the encounter around it is fiction.',
 'Jordan offers a question: “If I’m responsible for helping someone follow my argument, are they responsible for trying to follow it?” At the back, Mei has joined the class. She says, “I still need to know what an unfamiliar reader actually understands.”',
 'You can suggest one small investigation before the magazine deadline. What would tell you something useful?'],
 choices:[c('test','Ask two unfamiliar readers to paraphrase Lin’s claim and identify exactly where they lose the meaning.','The readers follow the claim but stumble over one local reference. Now you have a specific accessibility problem, not a verdict on an entire voice.',[4,5,3,0],['happy','happy'],[8,5,5,0]),c('compare','Compare the original and an edited version: what meaning, emphasis or relationship changes?','The edit clarifies a reference but flattens a joke about belonging. You now have evidence of a gain and a loss to discuss with Lin.',[4,5,3,0],['happy','neutral'],[5,5,5,4]),c('vote','Ask which version sounds more intelligent, without asking readers what they understood.','The room produces preferences. You still cannot tell whether the problem is unclear meaning, unfamiliarity, or a judgement about the speaker.',[1,0,0,0],['sad','sad'],[0,-3,-3,-3])]},
 {title:'Question round 1 · understand',background:'hall',cast:['young','lin'],speaker:'young',source:'B',text:[
 'The next source card names Young’s proposal. You have time to ask one question before the conversation moves on. All three paths will remain available for optional reading at the end.'],
 choices:[c('mix','What does code-meshing ask a writer to try?','“Put the sentence on the desk,” the imagined Young replies. “Try keeping the home-language expression while giving unfamiliar readers a way into its meaning. What does that let you do?” See card B for the published proposal.', [0,0,0,0]),c('rules','Does this mean conventions no longer matter?','“Show me the edit,” the imagined Young replies. “What does it help a reader understand? What does it change about the voice? Give those questions separate answers.” Read card D before treating code-meshing as the end of revision.',[0,0,0,0]),c('reader','What work could a reader do?','“What did you do when you met Jordan?” the imagined Young asks. “You could infer, ask, look something up—or make a judgement before listening. Which action gives you evidence?” Return to card A.', [0,0,0,0])]},
 {title:'Question round 2 · challenge',background:'hall',cast:['young','mei'],speaker:'mei',source:'D',text:[
 'Mei raises her hand. “I’m editing this week’s issue, not a future world where every reader already understands every expression. What should I do by Friday?” Choose the concern you most need to explore.'],
 choices:[c('clarity','What if the reader genuinely cannot understand a phrase?','“Then we have work to do,” the imagined Young replies. “Try context, an explanation, or a different example. Ask the reader again. Did the change solve the confusion you actually found?”',[0,0,0,0]),c('power','What if the evaluator still insists on a single standard?','“Whose risk are you choosing?” the imagined Young asks. “Lin has to live with Friday. Ask what that opportunity means before deciding what someone else should give up. Then explain what your advice does—and cannot do.”',[0,0,0,0]),c('dissent','Can I question the argument without dismissing it?','“Give the disagreement something to stand on,” the imagined Young replies. “State the limit, support it, then tell me what follows. I want an argument I can answer—not a smaller version of my claim that is easier to knock down.”',[0,0,0,0])]},
 {title:'Question round 3 · transfer',background:'hall',cast:['young','jordan'],speaker:'jordan',source:'C',text:[
 'Young directs everyone back to the essay’s sequence of objection and response. Card C is a reading guide, not a replacement for the passage. Open the article if you need the surrounding argument. Now choose where to take the discussion.'],
 choices:[c('china','How could we explore this in our multilingual school in China?','“Start with examples people choose to share,” the imagined Young suggests. “Who is speaking to whom, for what purpose? Then ask where the comparison helps and where it breaks.” This application does not equate multilingual school experiences with the essay’s racial history.',[0,0,0,0]),c('revise','What would a useful magazine revision actually change?','The imagined Young folds a page down the middle. “Here: what the edit helps readers understand. There: what it changes about the voice. Give Lin both columns, not just your conclusion.”',[0,0,0,0]),c('assess','What should fair assessment reward?','“Try assessing the argument before admiring its suit,” the imagined Young replies. “Where is the evidence? What connects it to the claim? Who can follow it? Now ask what the language choices are doing.”',[0,0,0,0])]},
 {title:'A reply that goes somewhere',background:'room',cast:['mei','lin'],speaker:'mei',text:[
 'After the lecture, the class gathers in a seminar room. Mei returns to the practical objection: “Our readers need to understand each other. One shared standard seems the fairest way to achieve that.”',
 'Lin asks you to draft the first move in a response. It must do more than disagree: it needs to move the proposal forward.'],
 choices:[c('bridge','“Shared understanding matters. Let’s test the confusing passages and add context where needed, rather than assuming every distinctive expression blocks understanding.”','Mei agrees to mark actual moments of confusion. Lin agrees to explain the local reference. You acknowledged the purpose, questioned the assumption, and proposed a way to act.',[5,3,8,5],['happy','happy'],[8,5,8,4]),c('qualify','“I want this readership, so I’ll discuss selected changes with Lin. But accepting an edit here wouldn’t prove the original voice is inferior.”','Mei can work with selected changes. Lin asks to review them individually. You made a context-specific recommendation while preserving a distinction the objection had blurred.',[5,3,8,5],['happy','neutral'],[7,5,8,2]),c('dismiss','“Anyone who needs a shared standard is prejudiced, so the magazine should publish the original immediately.”','Mei asks which passage a reader misunderstood and how your proposal helps. Lin still needs an answer. Naming a possible prejudice has not answered the concrete concern.',[0,0,0,1],['sad','sad'],[-5,-5,-6,1])]},
 {title:'The computer over there',background:'room',cast:['young','lin'],speaker:'young',text:[
 'In this fictional encounter, Young checks the time. “I have to go to the bathroom, but don’t worry: I’ve uploaded a facsimile of my consciousness into that computer over there. Feel free to ask it a question.”',
 'The computer lights up: DEFINITELY NOT A CONSCIOUSNESS. Underneath: “AI reading companion. I interpret a small, identified source bundle. I am not Young, cannot speak for him, and may get things wrong.” Lin laughs. “At least it knows what an objection is.”',
 'You may write one authentic question using the computer panel below. It is optional and never changes your score. Then decide what you will do with an answer.'],
 choices:[c('check','Check the answer against a source card and separate evidence from an inference.','Lin writes “verify” beside the answer. A useful interpretation still needs support; a cautious refusal can be more faithful than an invented certainty.',[0,7,3,2],['happy','happy'],[2,7,4,0]),c('follow','Use the answer to form a sharper question for the article, even if it does not settle my view.','Lin adds a question mark to the margin. You have turned an answer into a reading task and left room for another interpretation.',[0,7,3,2],['neutral','happy'],[2,5,4,3]),c('authority','Treat the answer as Young’s final view because the computer sounds confident.','The screen’s label has not disappeared. A simulation’s confidence cannot make its words the author’s own.',[0,0,0,0],['sad','sad'],[0,-7,-3,0])]},
 {title:'Friday’s issue',background:'room',cast:['lin','mei'],speaker:'lin',text:[
 'Young returns. In the imagined encounter he says, “I know I’ve talked a lot. I want to hear what you think now.” Mei has to close the issue soon. Lin is willing to follow any of the three plans below if you can explain it honestly.',
 'No option guarantees all the things Lin wants. The publication decision determines the ending, not your learning score. What do you recommend?'],
 choices:[c('preserve','Keep the distinctive language and decline blanket replacement, accepting that this issue may go ahead without the piece.','Lin keeps the voice and gives Mei a clear explanation. Mei cannot offer a slot under the current policy. Both can respect the decision and still be disappointed.',[3,0,3,5],['sad','sad'],[-2,0,3,8]),c('negotiate','Offer contextual clues and selected edits, with Lin approving every change.','Lin and Mei sit with the draft. The plan demands time from both of them. It will work better if your earlier advice made room for evidence and reader questions.',[3,0,3,5],['neutral','neutral'],[5,0,3,5]),c('adapt','Adapt this piece for the magazine’s preferred register, while retaining the original for another use.','Lin chooses the immediate readership and byline. Mei accepts. Lin wants the original preserved: this version has a purpose, but does not have to become the only available voice.',[3,0,3,5],['neutral','happy'],[5,0,3,-2])]},
 {title:'The ride home',background:'classroom',cast:['lin','jordan'],speaker:'lin',text:[
 'Back in the classroom, Mr. Hepting’s WeChat receipt says “Distance: one assumption.” The fare is inexplicably a dumpling. Lin opens the original draft beside the latest version.',
 'Before you see what happens later, return to your first promise. What belongs in the note you leave Lin?'],
 choices:[c('revisit','Name what changed my advice, what I still value, and one cost the decision does not solve.','Lin has a record of your reasoning, not just your verdict. Jordan can disagree with your recommendation and still follow how you reached it.',[4,4,8,4],['happy','happy'],[4,4,6,4]),c('defend','Keep my initial priority, but explain how evidence changed the way I would carry it out.','A revision in method can matter as much as a reversal of position. Lin can see both the continuity and the new understanding.',[4,4,8,4],['happy','neutral'],[4,4,6,4]),c('winning','Say the best decision is whichever gets the most applause.','Lin asks whose response counts and what the applause proves. A crowd’s approval cannot answer those questions by itself.',[0,0,0,0],['sad','sad'],[0,-3,-3,0])]}
];
export function ending(choices){
 const respectful=choices[1]!=='correct',careful=['test','compare'].includes(choices[2])&&choices[6]!=='dismiss';
 if(choices[8]==='preserve')return {title:'Another door, not a refund',paragraphs:['Friday’s magazine appears without Lin’s piece. The lost byline is real; no later invitation gives that particular opportunity back.',respectful?'Weeks later, Jordan remembers your conversation and invites Lin to pitch a piece to the independent zine. Its editor welcomes the voice and asks for stronger evidence. It is a smaller readership, a fresh task, and a better fit—not a guaranteed success.':'Weeks later, Lin finds an independent zine’s open call and prepares a new pitch. You did not build a working relationship with Jordan, so this route takes more searching. The call is an opportunity, not an acceptance.','Lin keeps working. Holding a boundary did not make the cost imaginary; the rejection did not make the story finished.']};
 if(choices[8]==='adapt')return {title:'A byline, and a second version',paragraphs:['The magazine publishes the adapted piece. Lin reaches readers who would not have seen the original and is proud of the argument.', 'A friend says it sounds more formal than the Lin they know. Lin feels that loss without regretting every edit. The original goes into a private folder for a later reading or publication. That possibility will still require work.','You can defend this choice without claiming everyone should make it. Lin chose a purpose and a cost; the magazine’s wider policy remains unresolved.']};
 return careful?{title:'A negotiated page',paragraphs:['Mei accepts the version with context and selected edits. Lin’s distinctive expressions remain where the explanation gives readers a way in. The revision costs an evening and the editor still receives a complaint.','The publication is a local success, not proof that every institution will negotiate. Mei suggests reviewing the policy after the issue. Lin asks to be part of that conversation.']}: {title:'The deadline passes',paragraphs:['Without a concrete account of what helps readers, the negotiation runs out of time. Mei postpones the piece; Lin is frustrated. Calling a proposal a compromise did not make it workable.','Lin asks for one more meeting after publication week. This time, you can bring marked passages, reader responses, and a narrower request. The setback leaves a next step—not a promised victory.']};
}
export function assessYoung(choices){
 if(!Array.isArray(choices)||choices.length>scenes.length)throw new Error('Invalid choice history');
 const scores=[0,0,0,0],indicators=[50,50,50,50];
 choices.forEach((id,i)=>{const choice=scenes[i].choices.find(c=>c.id===id);if(!choice)throw new Error('Illegal episode choice');choice.points.forEach((n,j)=>scores[j]+=n);choice.delta.forEach((n,j)=>indicators[j]=Math.max(0,Math.min(100,indicators[j]+n)));});
 // Normalize independent domain evidence to 25 points; publication choices score equally.
 scores.forEach((n,j)=>scores[j]=Math.round(n/[22,22,25,20][j]*25));
 return {complete:choices.length===scenes.length,scores,total:scores.reduce((a,b)=>a+b,0),indicators,ending:choices.length===scenes.length?ending(choices):null};
}

export const driverQuestions=[
 {prompt:'According to Young, what makes a dialect vulnerable to unfair treatment?',options:['The dialect’s inherent lack of reasoning','People’s attitudes toward its speakers','Every unfamiliar expression'],answer:1,note:'Card A places the problem in attitudes and prejudice, not an inherently defective language.'},
 {prompt:'Which revision best illustrates code-meshing?',options:['Keep a home-language expression and add context that helps this audience follow it','Remove every home-language feature before beginning the argument','Refuse all revision because conventions never matter'],answer:0,note:'Cards B and D support blending resources purposefully while continuing to attend to readers and craft.'},
 {prompt:'Which reply answers an objection while advancing the claim?',options:['Anyone who asks about clarity is prejudiced','Some readers may need context; test a clarification before requiring the writer to erase the expression','A writer should never think about unfamiliar readers'],answer:1,note:'Cards A–D distinguish a genuine comprehension problem from blanket judgement. The reply acknowledges the concern and proposes a next step.'},
 {prompt:'What can the magazine outcome establish?',options:['A rejected submission proves that its dialect cannot communicate','A later opportunity is guaranteed if the writer preserves every feature','An institution can impose a real cost without proving the writer’s language inferior'],answer:2,note:'The episode’s outcomes are fictional applications, not evidence from Young’s life. Card A helps distinguish institutional judgement from linguistic inferiority.'}
];
export function assessDriver(attempts=[]){
 if(!Array.isArray(attempts)||attempts.length>50)throw new Error('Invalid driver attempts');
 let passed=false,score=0;
 for(const answers of attempts){
  if(passed||!Array.isArray(answers)||answers.length!==4||answers.some(n=>!Number.isInteger(n)||n<0||n>2))throw new Error('Invalid driver answers');
  score=answers.reduce((sum,n,i)=>sum+Number(n===driverQuestions[i].answer),0);passed=score>=3;
 }
 return {passed,score};
}
