Config.history.maxStates=1;Config.history.controls=false;Config.saves.isAllowed=()=>false;Config.ui.stowBarInitially=true;Config.passages.nobr=true;
setup.choices=[];setup.driverAttempts=[];setup.channel=null;setup.ready=false;setup.booted=false;
Config.navigation.override=destination=>setup.ready?destination:'Start';
setup.send=(type,extra={})=>{if(parent!==window&&setup.channel)parent.postMessage({protocol:'episode-v1',episode:'own-english',version:1,channel:setup.channel,type,...extra},location.origin);};
setup.refresh=()=>Engine.play(setup.choices.length===10?(setup.assessDriver(setup.driverAttempts).passed?'Assessment':'Driver'):setup.choices.length?'Consequence'+setup.choices.length:'Decision1');
window.addEventListener('message',event=>{const m=event.data;if(event.origin!==location.origin||event.source!==parent||m?.protocol!=='episode-v1'||m.type!=='init'||m.episode!=='own-english'||m.version!==1||typeof m.channel!=='string')return;if(setup.ready){if(setup.booted){if(State.passage==='Start')setup.refresh();setup.send('started');}return;}try{setup.assess(m.choices);setup.assessDriver(m.driverAttempts||[]);}catch{return;}setup.channel=m.channel;setup.choices=m.choices.slice();setup.driverAttempts=(m.driverAttempts||[]).map(v=>v.slice());setup.ready=true;if(setup.booted){setup.refresh();setup.send('started');}});
const paragraph=(target,text)=>{const p=document.createElement('p');p.textContent=text;target.append(p);return p;};
Macro.add('ownChoice',{handler(){const [id,label]=this.args,step=setup.choices.length,b=document.createElement('button');b.className='stone-choice';b.textContent=label;b.onclick=()=>{if(b.disabled||setup.choices.length!==step)return;b.disabled=true;setup.choices.push(id);setup.send('save',{choices:setup.choices.slice()});Engine.play('Consequence'+(step+1));};this.output.append(b);}});
Macro.add('ownConsequence',{handler(){const i=Number(this.args[0]),c=setup.scenes[i].choices.find(c=>c.id===setup.choices[i]);paragraph(this.output,c.response);if(i>=3&&i<=5)paragraph(this.output,'Before you continue: put the answer into your own words and identify one change it could make to your advice. You will use that reasoning in the closing response.');}});
Macro.add('ownSource',{handler(){const ids=this.args.length?this.args:setup.sources.map(s=>s.id);for(const id of ids){const s=setup.sources.find(s=>s.id===id);if(!s)continue;const d=document.createElement('details');d.open=true;const title=document.createElement('summary');title.textContent='Source card '+s.id+' · '+s.title;d.append(title);if(s.quote){const q=document.createElement('blockquote');q.textContent=s.quote;d.append(q);paragraph(d,'Exact excerpt · Young, “Should Writers Use They Own English?”');}paragraph(d,s.note);const a=document.createElement('a');a.href=s.url||setup.sourceUrl;a.target='_blank';a.rel='noopener';a.textContent=s.url?'Read Young’s faculty statement':'Read the full article';d.append(a);this.output.append(d);}}});
Macro.add('ownStats',{handler(){const s=setup.assess(setup.choices),box=document.createElement('div');box.className='stone-stats';['Audience understanding','Credibility','Argument strength','Expression'].forEach((name,i)=>{const cell=document.createElement('div'),label=document.createElement('span'),n=document.createElement('strong');label.textContent=name;n.textContent=s.indicators[i]+'/100';cell.append(label,n);box.append(cell);});this.output.append(box);const d=document.createElement('details');d.innerHTML='<summary>What these indicators mean</summary><p>How well the people in this fictional situation understand each other, can rely on your claims, can follow your reasoning, and retain purposeful expression. These are narrative signals, not your learning grade. Reactions show characters’ concerns, not an answer key.</p>';this.output.append(d);}});
Macro.add('ownStage',{handler(){const i=Number(this.args[0]),s=setup.scenes[i],choice=this.args[1]?s.choices.find(c=>c.id===setup.choices[i]):null,stage=document.createElement('div');stage.className='stage';stage.style.backgroundImage='url("'+(s.background==='classroom'?'../../shared/classroom-v1.webp':s.background+'.webp')+'")';stage.setAttribute('aria-label',s.background==='hall'?'Lecture hall':s.background==='room'?'Seminar room with computer':'Classroom');s.cast.forEach((id,j)=>{const mood=choice?.reactions[j]||'neutral',figure=document.createElement('figure'),sprite=document.createElement('div'),caption=document.createElement('figcaption');figure.className='character '+(s.speaker===id?'speaking':'');sprite.className='sprite';sprite.style.backgroundImage='url("'+id+'.webp")';sprite.style.backgroundPosition=({neutral:'0%',happy:'50%',sad:'100%'})[mood]+' 0';sprite.setAttribute('role','img');sprite.setAttribute('aria-label',setup.characters[id]+' · '+({neutral:'thoughtful',happy:'relieved',sad:'troubled'})[mood]);caption.textContent=setup.characters[id].split(' · ')[0]+' · '+({neutral:'thoughtful',happy:'relieved',sad:'troubled'})[mood];figure.append(sprite,caption);stage.append(figure);});this.output.append(stage);}});
Macro.add('ownComputer',{handler(){paragraph(this.output,'One optional question, in your own words. An AI interpretation, not the author’s words. Requires a connection.');const b=document.createElement('button');b.textContent='Ask the reading companion';b.onclick=()=>{if(parent===window){paragraph(this.output,'Open this episode inside your class to use the AI companion. You can still write your question in your notebook.');b.disabled=true;}else setup.send('question');};this.output.append(b);}});
Macro.add('ownAssessment',{handler(){paragraph(this.output,'The driver checks your fare: '+setup.assessDriver(setup.driverAttempts).score+'/4. He starts the engine. The lecture hall dissolves into familiar streets, and the class returns with an argument still worth having. The next adventure is forthcoming.');const a=setup.assess(setup.choices),h=document.createElement('h2');h.textContent=a.ending.title;this.output.append(h);a.ending.paragraphs.forEach(p=>paragraph(this.output,p));paragraph(this.output,'Your first promise: '+setup.scenes[0].choices.find(c=>c.id===setup.choices[0]).label);paragraph(this.output,'Your final reflection: '+setup.scenes[9].choices.find(c=>c.id===setup.choices[9]).response);const score=paragraph(this.output,a.total+' / 100 · Decision evidence');score.className='score';['Rhetorical situation','Claims and evidence','Reasoning and organization','Style'].forEach((name,i)=>paragraph(this.output,name+': '+a.scores[i]+'/25'));const d=document.createElement('details'),sum=document.createElement('summary');sum.textContent='See the scoring evidence';d.append(sum);paragraph(d,'Each domain is normalized to 25 points from available evidence (22, 22, 25 and 20 raw points). Question selection earns no points; all three publication paths earn equal points. The writing response receives separate AI feedback, never an automatic grade.');setup.choices.forEach((id,i)=>{const c=setup.scenes[i].choices.find(c=>c.id===id);paragraph(d,(i+1)+'. '+c.label+' — raw evidence: '+c.points.join(' / '));});this.output.append(d);const min=a.scores.indexOf(Math.min(...a.scores));paragraph(this.output,'Try next: '+['Specify what the writer and reader each need.','Distinguish source evidence from your inference, and test a claim before judging it.','Answer the strongest version of the objection, then explain what should happen next.','Explain why a particular language choice serves this audience and purpose.'][min]);paragraph(this.output,setup.prompt);const b=document.createElement('button');b.textContent='Write my closing analysis';b.onclick=()=>parent===window?paragraph(this.output,'Class access is needed for saved writing and live AI feedback. Keep your response in your notebook for this standalone preview.'):setup.send('analysis');this.output.append(b);setup.send('complete',{choices:setup.choices.slice(),driverAttempts:setup.driverAttempts});}});

// Passage-local pacing never changes the immutable choice history or score.
setup.cancelReveal=()=>{};
$(document).on(':passageinit',()=>setup.cancelReveal());
$(document).on(':passagedisplay',function(){
 const passage=document.querySelector('.passage'),beats=passage.querySelector('.story-beats'),after=passage.querySelector('.after-beats');
 if(beats&&after){
  const paragraphs=Array.from(beats.children);const full=document.createElement('div');full.className='sr-only';full.innerHTML=beats.innerHTML;beats.before(full);beats.setAttribute('aria-hidden','true');let index=0,timer=null,finish=()=>{};
  const controls=document.createElement('div');controls.className='beat-controls';
  const next=document.createElement('button'),all=document.createElement('button'),counter=document.createElement('span');
  next.textContent='Next ▸';all.textContent='Show all';all.className='quiet';counter.className='beat-count';
  controls.append(counter,next,all);beats.after(controls);after.hidden=true;
  const stop=()=>{if(timer)clearInterval(timer);timer=null;};setup.cancelReveal=stop;
  const show=()=>{
   stop();paragraphs.forEach((p,i)=>p.hidden=i!==index);const p=paragraphs[index];
   counter.textContent=(index+1)+' / '+paragraphs.length;next.textContent=index===paragraphs.length-1?'Continue ▸':'Next ▸';
   // Keep full accessible text; the optional visual reveal never delays screen readers.
   const original=p.innerHTML;finish=()=>{stop();p.innerHTML=original;};
   if(!matchMedia('(prefers-reduced-motion: reduce)').matches){
    const accessible=document.createElement('span');accessible.className='sr-only';accessible.innerHTML=original;
    const visual=document.createElement('span');visual.setAttribute('aria-hidden','true');visual.innerHTML=original;
    p.replaceChildren(accessible,visual);const walker=document.createTreeWalker(visual,NodeFilter.SHOW_TEXT),nodes=[];let node;
    while((node=walker.nextNode()))nodes.push({node,text:node.textContent});nodes.forEach(n=>n.node.textContent='');
    let n=0,c=0;timer=setInterval(()=>{for(let j=0;j<3&&n<nodes.length;j++){const entry=nodes[n];entry.node.textContent=entry.text.slice(0,++c);if(c>=entry.text.length){n++;c=0;}}if(n===nodes.length)finish();},16);
   }
  };
  const unlock=(showAll=false)=>{finish();if(showAll)paragraphs.forEach(p=>p.hidden=false);else{const recall=document.createElement('details');recall.innerHTML='<summary>Recall the conversation</summary>'+paragraphs.map(p=>'<p>'+p.innerHTML+'</p>').join('');after.prepend(recall);}controls.remove();after.hidden=false;const target=after.querySelector('summary,button');target?.focus({preventScroll:true});};
  next.addEventListener('click',()=>{if(timer){finish();return;}if(index<paragraphs.length-1){index++;show();}else unlock();});
  all.addEventListener('click',()=>unlock(true));show();
 }
 const h=passage.querySelector('h1');if(h){h.setAttribute('tabindex','-1');h.focus({preventScroll:true});}window.scrollTo(0,0);
});

$(document).one(':storyready',()=>{setup.booted=true;if(setup.channel){setup.refresh();setup.send('started');}if(parent===window){setup.ready=true;return;}parent.postMessage({protocol:'episode-v1',episode:'own-english',version:1,type:'ready'},location.origin);});

Macro.add('ownQuestionSource',{handler(){const i=Number(this.args[0]),id=i===3?({mix:'B',rules:'D',reader:'A'})[setup.choices[i]]:i===4?'D':'C';new Wikifier(this.output,'<<ownSource '+JSON.stringify(id)+'>>');}});

Macro.add('ownDriver',{handler(){
 const root=this.output,heading=document.createElement('h1');heading.textContent='The fare for the ride home';root.append(heading);
 paragraph(root,'The driver lowers his sunglasses. “Four questions. Three correct pays the fare. If you miss it, we review and try again. Nobody is being left behind.”');
 const previous=setup.assessDriver(setup.driverAttempts);
 if(setup.driverAttempts.length){paragraph(root,'Last check: '+previous.score+'/4. Your journey choices are safe.');const answers=setup.driverAttempts.at(-1);setup.driverQuestions.forEach((q,i)=>{if(answers[i]!==q.answer)paragraph(root,'Review '+(i+1)+': '+q.note);});}
 const form=document.createElement('form');root.append(form);
 setup.driverQuestions.forEach((q,i)=>{const group=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=(i+1)+'. '+q.prompt;group.append(legend);q.options.forEach((text,n)=>{const label=document.createElement('label'),input=document.createElement('input');input.type='radio';input.name='fare-'+i;input.value=n;input.required=true;label.append(input,document.createTextNode(' '+text));label.style.display='block';label.style.padding='0.5rem';group.append(label);});form.append(group);});
 const button=document.createElement('button');button.type='submit';button.textContent='Check my fare';form.append(button);
 form.onsubmit=event=>{event.preventDefault();if(!form.reportValidity())return;button.disabled=true;const answers=setup.driverQuestions.map((_,i)=>Number(new FormData(form).get('fare-'+i)));setup.driverAttempts.push(answers);setup.send('save',{choices:setup.choices.slice(),driverAttempts:setup.driverAttempts});setup.refresh();};
 const review=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Review the source cards';review.append(summary);new Wikifier(review,'<<ownSource>>');root.append(review);
}});
